-- ~/.config/nvim/colors/mini.lua
-- A minimal, modern dark colorscheme with restrained color usage

local colors = {
  -- Base palette (desaturated, warm-dark)
  bg = "#1a1a1a", -- Deep charcoal, not pure black
  bg_dark = "#141414", -- Darker for statuslines/floats
  bg_light = "#252525", -- Lighter for visual selection
  bg_highlight = "#2a2a2a", -- Current line, menus

  -- Foreground (warm gray, easy on eyes)
  fg = "#d4c5b0", -- Warm beige-gray primary text
  fg_dim = "#8a7f72", -- Muted for comments/secondary
  fg_bright = "#e8dcc8", -- Brighter for emphasis

  -- Accent colors (very restrained - 3 main hues only)
  -- Warm amber for important/keywords
  amber = "#c4a574",
  amber_dim = "#8b7355",

  -- Muted sage for strings/success
  sage = "#8b9a7d",
  sage_dim = "#5a6b52",

  -- Soft blue for functions/info (desaturated)
  blue = "#7a8b9a",
  blue_dim = "#4a5560",

  -- Error/warning (still muted)
  red = "#b06b6b",
  yellow = "#b8a066",

  -- UI grays
  gray_1 = "#3a3a3a", -- Borders, separators
  gray_2 = "#4a4a4a", -- Active elements
  gray_3 = "#606060", -- Non-active
}

local function set_highlight(group, opts)
  local cmd = string.format("highlight %s", group)
  if opts.fg then
    cmd = cmd .. string.format(" guifg=%s", opts.fg)
  end
  if opts.bg then
    cmd = cmd .. string.format(" guibg=%s", opts.bg)
  end
  if opts.sp then
    cmd = cmd .. string.format(" guisp=%s", opts.sp)
  end
  if opts.style then
    cmd = cmd .. string.format(" gui=%s", opts.style)
  end
  vim.cmd(cmd)
end

-- Reset highlights
vim.cmd "highlight clear"
if vim.fn.exists "syntax_on" then
  vim.cmd "syntax reset"
end
vim.g.colors_name = "minimalist"

-- Editor UI
set_highlight("Normal", { fg = colors.fg, bg = colors.bg })
set_highlight("NormalFloat", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("FloatBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("Cursor", { fg = colors.bg, bg = colors.fg_bright })
set_highlight("CursorLine", { bg = colors.bg_highlight })
set_highlight("CursorColumn", { bg = colors.bg_highlight })
set_highlight("LineNr", { fg = colors.gray_3 })
set_highlight("CursorLineNr", { fg = colors.amber, style = "bold" })
set_highlight("SignColumn", { bg = colors.bg })
set_highlight("ColorColumn", { bg = colors.bg_light })

-- Selection
set_highlight("Visual", { bg = colors.bg_light })
set_highlight("VisualNOS", { bg = colors.bg_light })

-- Search
set_highlight("Search", { fg = colors.bg, bg = colors.amber })
set_highlight("IncSearch", { fg = colors.bg, bg = colors.amber_dim, style = "bold" })
set_highlight("CurSearch", { fg = colors.bg, bg = colors.amber, style = "bold" })

-- Matching
set_highlight("MatchParen", { fg = colors.amber, style = "bold" })

-- Status line
set_highlight("StatusLine", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("StatusLineNC", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("StatusLineTerm", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("StatusLineTermNC", { fg = colors.fg_dim, bg = colors.bg_dark })

-- Tabs
set_highlight("TabLine", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("TabLineFill", { bg = colors.bg_dark })
set_highlight("TabLineSel", { fg = colors.fg, bg = colors.bg, style = "bold" })

-- Windows
set_highlight("WinSeparator", { fg = colors.gray_1 })
set_highlight("VertSplit", { fg = colors.gray_1 })

-- Popups
set_highlight("Pmenu", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("PmenuSel", { fg = colors.bg, bg = colors.amber })
set_highlight("PmenuSbar", { bg = colors.bg_light })
set_highlight("PmenuThumb", { bg = colors.gray_2 })

-- Syntax highlighting (minimal color usage)
set_highlight("Comment", { fg = colors.fg_dim, style = "italic" })
set_highlight("Constant", { fg = colors.sage })
set_highlight("String", { fg = colors.sage })
set_highlight("Character", { fg = colors.sage })
set_highlight("Number", { fg = colors.amber_dim })
set_highlight("Boolean", { fg = colors.amber_dim, style = "bold" })
set_highlight("Float", { fg = colors.amber_dim })

set_highlight("Identifier", { fg = colors.fg })
set_highlight("Function", { fg = colors.blue })

set_highlight("Statement", { fg = colors.fg_bright, style = "bold" })
set_highlight("Conditional", { fg = colors.fg_bright, style = "bold" })
set_highlight("Repeat", { fg = colors.fg_bright, style = "bold" })
set_highlight("Label", { fg = colors.amber })
set_highlight("Operator", { fg = colors.fg_dim })
set_highlight("Keyword", { fg = colors.amber, style = "bold" })
set_highlight("Exception", { fg = colors.amber, style = "bold" })

set_highlight("PreProc", { fg = colors.amber_dim })
set_highlight("Include", { fg = colors.amber_dim })
set_highlight("Define", { fg = colors.amber_dim })
set_highlight("Macro", { fg = colors.amber_dim })
set_highlight("PreCondit", { fg = colors.amber_dim })

set_highlight("Type", { fg = colors.blue })
set_highlight("StorageClass", { fg = colors.blue })
set_highlight("Structure", { fg = colors.blue })
set_highlight("Typedef", { fg = colors.blue })

set_highlight("Special", { fg = colors.amber })
set_highlight("SpecialChar", { fg = colors.amber })
set_highlight("Tag", { fg = colors.amber })
set_highlight("Delimiter", { fg = colors.gray_3 })
set_highlight("SpecialComment", { fg = colors.fg_dim, style = "bold" })
set_highlight("Debug", { fg = colors.red })

set_highlight("Underlined", { fg = colors.blue, style = "underline" })
set_highlight("Ignore", { fg = colors.gray_3 })
set_highlight("Error", { fg = colors.red, style = "bold" })
set_highlight("Todo", { fg = colors.amber, bg = colors.bg_light, style = "bold" })

-- Diagnostics (modern, subtle)
set_highlight("DiagnosticError", { fg = colors.red })
set_highlight("DiagnosticWarn", { fg = colors.yellow })
set_highlight("DiagnosticInfo", { fg = colors.blue })
set_highlight("DiagnosticHint", { fg = colors.sage_dim })
set_highlight("DiagnosticOk", { fg = colors.sage })

set_highlight("DiagnosticUnderlineError", { sp = colors.red, style = "undercurl" })
set_highlight("DiagnosticUnderlineWarn", { sp = colors.yellow, style = "undercurl" })
set_highlight("DiagnosticUnderlineInfo", { sp = colors.blue, style = "undercurl" })
set_highlight("DiagnosticUnderlineHint", { sp = colors.sage_dim, style = "undercurl" })

set_highlight("DiagnosticVirtualTextError", { fg = colors.red, bg = "#2a1f1f" })
set_highlight("DiagnosticVirtualTextWarn", { fg = colors.yellow, bg = "#2a2520" })
set_highlight("DiagnosticVirtualTextInfo", { fg = colors.blue, bg = "#1f252a" })
set_highlight("DiagnosticVirtualTextHint", { fg = colors.sage_dim, bg = "#1f2a1f" })

-- Treesitter (modern, consistent)
set_highlight("@variable", { fg = colors.fg })
set_highlight("@variable.builtin", { fg = colors.amber_dim, style = "italic" })
set_highlight("@variable.parameter", { fg = colors.fg })
set_highlight("@variable.member", { fg = colors.fg })

set_highlight("@constant", { fg = colors.sage })
set_highlight("@constant.builtin", { fg = colors.sage, style = "bold" })
set_highlight("@constant.macro", { fg = colors.sage_dim })

set_highlight("@module", { fg = colors.blue })
set_highlight("@module.builtin", { fg = colors.blue, style = "bold" })

set_highlight("@label", { fg = colors.amber })
set_highlight("@string", { fg = colors.sage })
set_highlight("@string.documentation", { fg = colors.sage_dim })
set_highlight("@string.regex", { fg = colors.amber })
set_highlight("@string.escape", { fg = colors.amber_dim })
set_highlight("@string.special", { fg = colors.amber })

set_highlight("@character", { fg = colors.sage })
set_highlight("@character.special", { fg = colors.amber })

set_highlight("@boolean", { fg = colors.amber_dim, style = "bold" })
set_highlight("@number", { fg = colors.amber_dim })
set_highlight("@number.float", { fg = colors.amber_dim })

set_highlight("@type", { fg = colors.blue })
set_highlight("@type.builtin", { fg = colors.blue, style = "bold" })
set_highlight("@type.definition", { fg = colors.blue })

set_highlight("@attribute", { fg = colors.amber })
set_highlight("@attribute.builtin", { fg = colors.amber, style = "bold" })
set_highlight("@property", { fg = colors.fg })

set_highlight("@function", { fg = colors.blue })
set_highlight("@function.builtin", { fg = colors.blue, style = "bold" })
set_highlight("@function.call", { fg = colors.blue })
set_highlight("@function.macro", { fg = colors.amber_dim })

set_highlight("@function.method", { fg = colors.blue })
set_highlight("@function.method.call", { fg = colors.blue })

set_highlight("@constructor", { fg = colors.blue, style = "bold" })
set_highlight("@operator", { fg = colors.fg_dim })

set_highlight("@keyword", { fg = colors.amber, style = "bold" })
set_highlight("@keyword.coroutine", { fg = colors.amber })
set_highlight("@keyword.function", { fg = colors.amber })
set_highlight("@keyword.operator", { fg = colors.amber })
set_highlight("@keyword.import", { fg = colors.amber_dim })
set_highlight("@keyword.type", { fg = colors.amber })
set_highlight("@keyword.modifier", { fg = colors.amber })
set_highlight("@keyword.repeat", { fg = colors.amber })
set_highlight("@keyword.return", { fg = colors.amber })
set_highlight("@keyword.debug", { fg = colors.red })
set_highlight("@keyword.exception", { fg = colors.amber })

set_highlight("@keyword.conditional", { fg = colors.amber })
set_highlight("@keyword.conditional.ternary", { fg = colors.amber })
set_highlight("@keyword.directive", { fg = colors.amber_dim })
set_highlight("@keyword.directive.define", { fg = colors.amber_dim })

set_highlight("@punctuation.delimiter", { fg = colors.gray_3 })
set_highlight("@punctuation.bracket", { fg = colors.gray_3 })
set_highlight("@punctuation.special", { fg = colors.amber })

set_highlight("@comment", { fg = colors.fg_dim, style = "italic" })
set_highlight("@comment.documentation", { fg = colors.fg_dim, style = "italic" })

set_highlight("@comment.error", { fg = colors.red, style = "bold" })
set_highlight("@comment.warning", { fg = colors.yellow, style = "bold" })
set_highlight("@comment.todo", { fg = colors.amber, style = "bold" })
set_highlight("@comment.note", { fg = colors.blue, style = "bold" })

set_highlight("@markup.strong", { style = "bold" })
set_highlight("@markup.italic", { style = "italic" })
set_highlight("@markup.strikethrough", { style = "strikethrough" })
set_highlight("@markup.underline", { style = "underline" })

set_highlight("@markup.heading", { fg = colors.amber, style = "bold" })
set_highlight("@markup.heading.1", { fg = colors.amber, style = "bold" })
set_highlight("@markup.heading.2", { fg = colors.amber_dim, style = "bold" })
set_highlight("@markup.heading.3", { fg = colors.amber_dim, style = "bold" })
set_highlight("@markup.heading.4", { fg = colors.amber_dim, style = "bold" })
set_highlight("@markup.heading.5", { fg = colors.amber_dim, style = "bold" })
set_highlight("@markup.heading.6", { fg = colors.amber_dim, style = "bold" })

set_highlight("@markup.quote", { fg = colors.fg_dim, style = "italic" })
set_highlight("@markup.math", { fg = colors.sage })
set_highlight("@markup.link", { fg = colors.blue, style = "underline" })
set_highlight("@markup.link.label", { fg = colors.amber })
set_highlight("@markup.link.url", { fg = colors.blue, style = "underline" })

set_highlight("@markup.raw", { fg = colors.sage })
set_highlight("@markup.raw.block", { fg = colors.sage_dim })

set_highlight("@markup.list", { fg = colors.amber })
set_highlight("@markup.list.checked", { fg = colors.sage })
set_highlight("@markup.list.unchecked", { fg = colors.gray_3 })

set_highlight("@diff.plus", { fg = colors.sage })
set_highlight("@diff.minus", { fg = colors.red })
set_highlight("@diff.delta", { fg = colors.blue })

set_highlight("@tag", { fg = colors.amber })
set_highlight("@tag.builtin", { fg = colors.amber, style = "bold" })
set_highlight("@tag.attribute", { fg = colors.blue })
set_highlight("@tag.delimiter", { fg = colors.gray_3 })

-- Git
set_highlight("GitSignsAdd", { fg = colors.sage })
set_highlight("GitSignsChange", { fg = colors.blue })
set_highlight("GitSignsDelete", { fg = colors.red })
set_highlight("GitSignsAddLn", { bg = "#1f2a1f" })
set_highlight("GitSignsChangeLn", { bg = "#1f252a" })
set_highlight("GitSignsDeleteLn", { bg = "#2a1f1f" })

-- Telescope (modern floating window)
set_highlight("TelescopeNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("TelescopeBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("TelescopePromptNormal", { fg = colors.fg, bg = colors.bg_light })
set_highlight("TelescopePromptBorder", { fg = colors.gray_1, bg = colors.bg_light })
set_highlight("TelescopePromptTitle", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("TelescopePreviewTitle", { fg = colors.bg, bg = colors.blue, style = "bold" })
set_highlight("TelescopeResultsTitle", { fg = colors.bg, bg = colors.sage, style = "bold" })
set_highlight("TelescopeSelection", { fg = colors.fg_bright, bg = colors.bg_highlight, style = "bold" })
set_highlight("TelescopeSelectionCaret", { fg = colors.amber })
set_highlight("TelescopeMatching", { fg = colors.amber, style = "bold" })

-- Neo-tree / Nvim-tree
set_highlight("NeoTreeNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NeoTreeNormalNC", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NeoTreeRootName", { fg = colors.amber, style = "bold" })
set_highlight("NeoTreeDirectoryName", { fg = colors.fg })
set_highlight("NeoTreeDirectoryIcon", { fg = colors.blue })
set_highlight("NeoTreeFileName", { fg = colors.fg })
set_highlight("NeoTreeFileIcon", { fg = colors.sage })
set_highlight("NeoTreeGitAdded", { fg = colors.sage })
set_highlight("NeoTreeGitModified", { fg = colors.blue })
set_highlight("NeoTreeGitDeleted", { fg = colors.red })
set_highlight("NeoTreeIndentMarker", { fg = colors.gray_1 })

-- Which-key
set_highlight("WhichKey", { fg = colors.amber, style = "bold" })
set_highlight("WhichKeyGroup", { fg = colors.blue })
set_highlight("WhichKeyDesc", { fg = colors.fg })
set_highlight("WhichKeySeparator", { fg = colors.gray_3 })
set_highlight("WhichKeyValue", { fg = colors.sage })

-- Indent blankline
set_highlight("IblIndent", { fg = colors.gray_1 })
set_highlight("IblScope", { fg = colors.gray_3 })

-- Notify
set_highlight("NotifyBackground", { bg = colors.bg_dark })
set_highlight("NotifyERRORBorder", { fg = colors.red })
set_highlight("NotifyWARNBorder", { fg = colors.yellow })
set_highlight("NotifyINFOBorder", { fg = colors.blue })
set_highlight("NotifyDEBUGBorder", { fg = colors.gray_3 })
set_highlight("NotifyTRACEBorder", { fg = colors.sage })
set_highlight("NotifyERRORIcon", { fg = colors.red })
set_highlight("NotifyWARNIcon", { fg = colors.yellow })
set_highlight("NotifyINFOIcon", { fg = colors.blue })
set_highlight("NotifyDEBUGIcon", { fg = colors.gray_3 })
set_highlight("NotifyTRACEIcon", { fg = colors.sage })
set_highlight("NotifyERRORTitle", { fg = colors.red })
set_highlight("NotifyWARNTitle", { fg = colors.yellow })
set_highlight("NotifyINFOTitle", { fg = colors.blue })
set_highlight("NotifyDEBUGTitle", { fg = colors.gray_3 })
set_highlight("NotifyTRACETitle", { fg = colors.sage })

-- Cmp (completion)
set_highlight("CmpItemAbbr", { fg = colors.fg })
set_highlight("CmpItemAbbrDeprecated", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("CmpItemAbbrMatch", { fg = colors.amber, style = "bold" })
set_highlight("CmpItemAbbrMatchFuzzy", { fg = colors.amber, style = "bold" })
set_highlight("CmpItemKind", { fg = colors.blue })
set_highlight("CmpItemMenu", { fg = colors.fg_dim })
set_highlight("CmpItemKindText", { fg = colors.fg })
set_highlight("CmpItemKindMethod", { fg = colors.blue })
set_highlight("CmpItemKindFunction", { fg = colors.blue })
set_highlight("CmpItemKindConstructor", { fg = colors.blue })
set_highlight("CmpItemKindField", { fg = colors.sage })
set_highlight("CmpItemKindVariable", { fg = colors.fg })
set_highlight("CmpItemKindClass", { fg = colors.blue })
set_highlight("CmpItemKindInterface", { fg = colors.blue })
set_highlight("CmpItemKindModule", { fg = colors.blue })
set_highlight("CmpItemKindProperty", { fg = colors.sage })
set_highlight("CmpItemKindUnit", { fg = colors.amber_dim })
set_highlight("CmpItemKindValue", { fg = colors.amber_dim })
set_highlight("CmpItemKindEnum", { fg = colors.blue })
set_highlight("CmpItemKindKeyword", { fg = colors.amber })
set_highlight("CmpItemKindSnippet", { fg = colors.sage })
set_highlight("CmpItemKindColor", { fg = colors.amber })
set_highlight("CmpItemKindFile", { fg = colors.blue })
set_highlight("CmpItemKindReference", { fg = colors.amber })
set_highlight("CmpItemKindFolder", { fg = colors.blue })
set_highlight("CmpItemKindEnumMember", { fg = colors.sage })
set_highlight("CmpItemKindConstant", { fg = colors.sage })
set_highlight("CmpItemKindStruct", { fg = colors.blue })
set_highlight("CmpItemKindEvent", { fg = colors.amber })
set_highlight("CmpItemKindOperator", { fg = colors.fg_dim })
set_highlight("CmpItemKindTypeParameter", { fg = colors.blue })

-- Lazy (plugin manager)
set_highlight("LazyButton", { fg = colors.fg, bg = colors.bg_light })
set_highlight("LazyButtonActive", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("LazyComment", { fg = colors.fg_dim })
set_highlight("LazyCommit", { fg = colors.sage })
set_highlight("LazyCommitIssue", { fg = colors.red })
set_highlight("LazyCommitType", { fg = colors.amber })
set_highlight("LazyDir", { fg = colors.blue })
set_highlight("LazyH1", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("LazyH2", { fg = colors.amber, style = "bold" })
set_highlight("LazyProp", { fg = colors.blue })
set_highlight("LazyReasonCmd", { fg = colors.amber })
set_highlight("LazyReasonEvent", { fg = colors.amber })
set_highlight("LazyReasonFt", { fg = colors.blue })
set_highlight("LazyReasonImport", { fg = colors.amber_dim })
set_highlight("LazyReasonKeys", { fg = colors.amber })
set_highlight("LazyReasonPlugin", { fg = colors.blue })
set_highlight("LazyReasonRuntime", { fg = colors.amber_dim })
set_highlight("LazyReasonSource", { fg = colors.sage })
set_highlight("LazyReasonStart", { fg = colors.sage })
set_highlight("LazySpecial", { fg = colors.amber })
set_highlight("LazyTaskError", { fg = colors.red })
set_highlight("LazyTaskOutput", { fg = colors.fg })
set_highlight("LazyUrl", { fg = colors.blue, style = "underline" })
set_highlight("LazyValue", { fg = colors.sage })

-- Mason
set_highlight("MasonHeader", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("MasonHeaderSecondary", { fg = colors.bg, bg = colors.blue, style = "bold" })
set_highlight("MasonHighlight", { fg = colors.amber })
set_highlight("MasonHighlightBlock", { fg = colors.bg, bg = colors.amber })
set_highlight("MasonHighlightBlockBold", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("MasonHighlightSecondary", { fg = colors.blue })
set_highlight("MasonHighlightBlockSecondary", { fg = colors.bg, bg = colors.blue })
set_highlight("MasonHighlightBlockBoldSecondary", { fg = colors.bg, bg = colors.blue, style = "bold" })
set_highlight("MasonMuted", { fg = colors.fg_dim })
set_highlight("MasonMutedBlock", { fg = colors.fg, bg = colors.bg_light })
set_highlight("MasonMutedBlockBold", { fg = colors.fg, bg = colors.bg_light, style = "bold" })

-- Dashboard (Alpha)
set_highlight("DashboardHeader", { fg = colors.amber })
set_highlight("DashboardCenter", { fg = colors.fg })
set_highlight("DashboardFooter", { fg = colors.fg_dim, style = "italic" })
set_highlight("DashboardShortcut", { fg = colors.blue })
set_highlight("DashboardDesc", { fg = colors.fg })
set_highlight("DashboardKey", { fg = colors.amber, style = "bold" })
set_highlight("DashboardIcon", { fg = colors.sage })

-- Illuminated (LSP word highlight)
set_highlight("IlluminatedWordText", { bg = colors.bg_light })
set_highlight("IlluminatedWordRead", { bg = colors.bg_light })
set_highlight("IlluminatedWordWrite", { bg = colors.bg_light })

-- Hop / Leap / Flash
set_highlight("HopNextKey", { fg = colors.amber, style = "bold" })
set_highlight("HopNextKey1", { fg = colors.amber, style = "bold" })
set_highlight("HopNextKey2", { fg = colors.amber_dim })
set_highlight("HopUnmatched", { fg = colors.gray_3 })
set_highlight("LeapMatch", { fg = colors.amber, style = "bold" })
set_highlight("LeapLabelPrimary", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("LeapLabelSecondary", { fg = colors.bg, bg = colors.blue, style = "bold" })
set_highlight("LeapBackdrop", { fg = colors.gray_3 })

-- Fidget (LSP progress)
set_highlight("FidgetTitle", { fg = colors.amber, style = "bold" })
set_highlight("FidgetTask", { fg = colors.fg_dim })

-- Noice (modern UI)
set_highlight("NoiceCmdline", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoiceCmdlineIcon", { fg = colors.amber })
set_highlight("NoiceCmdlineIconSearch", { fg = colors.amber })
set_highlight("NoiceCmdlinePopup", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoiceCmdlinePopupBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("NoiceCmdlinePopupBorderSearch", { fg = colors.amber, bg = colors.bg_dark })
set_highlight("NoiceConfirm", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoiceConfirmBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("NoiceCursor", { fg = colors.bg, bg = colors.fg })
set_highlight("NoiceFormatLevelError", { fg = colors.red })
set_highlight("NoiceFormatLevelWarn", { fg = colors.yellow })
set_highlight("NoiceFormatLevelInfo", { fg = colors.blue })
set_highlight("NoiceFormatLevelDebug", { fg = colors.gray_3 })
set_highlight("NoiceFormatLevelTrace", { fg = colors.sage })
set_highlight("NoiceLspProgressClient", { fg = colors.amber })
set_highlight("NoiceLspProgressSpinner", { fg = colors.amber })
set_highlight("NoiceLspProgressTitle", { fg = colors.fg_dim })
set_highlight("NoiceMini", { fg = colors.fg_dim })
set_highlight("NoicePopup", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoicePopupBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("NoicePopupmenu", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoicePopupmenuBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("NoicePopupmenuMatch", { fg = colors.amber, style = "bold" })
set_highlight("NoicePopupmenuSelected", { fg = colors.bg, bg = colors.amber })
set_highlight("NoiceScrollbar", { fg = colors.gray_2, bg = colors.bg_light })
set_highlight("NoiceScrollbarThumb", { fg = colors.gray_3 })
set_highlight("NoiceSplit", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NoiceSplitBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("NoiceVirtualText", { fg = colors.fg_dim })

-- Buffer line (if used)
set_highlight("BufferLineFill", { bg = colors.bg_dark })
set_highlight("BufferLineBackground", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("BufferLineBufferVisible", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("BufferLineBufferSelected", { fg = colors.fg, bg = colors.bg, style = "bold" })
set_highlight("BufferLineTab", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("BufferLineTabSelected", { fg = colors.fg, bg = colors.bg, style = "bold" })
set_highlight("BufferLineTabClose", { fg = colors.red, bg = colors.bg_dark })
set_highlight("BufferLineIndicatorSelected", { fg = colors.amber, bg = colors.bg })
set_highlight("BufferLineSeparator", { fg = colors.bg_dark, bg = colors.bg_dark })
set_highlight("BufferLineSeparatorVisible", { fg = colors.bg_dark, bg = colors.bg_dark })
set_highlight("BufferLineSeparatorSelected", { fg = colors.bg_dark, bg = colors.bg })
set_highlight("BufferLineCloseButton", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("BufferLineCloseButtonVisible", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("BufferLineCloseButtonSelected", { fg = colors.red, bg = colors.bg })
set_highlight("BufferLineModified", { fg = colors.sage, bg = colors.bg_dark })
set_highlight("BufferLineModifiedVisible", { fg = colors.sage, bg = colors.bg_dark })
set_highlight("BufferLineModifiedSelected", { fg = colors.sage, bg = colors.bg })
set_highlight("BufferLineDuplicate", { fg = colors.fg_dim, bg = colors.bg_dark, style = "italic" })
set_highlight("BufferLineDuplicateSelected", { fg = colors.fg, bg = colors.bg, style = "italic" })
set_highlight("BufferLineDuplicateVisible", { fg = colors.fg_dim, bg = colors.bg_dark, style = "italic" })
set_highlight("BufferLinePick", { fg = colors.amber, bg = colors.bg_dark, style = "bold" })
set_highlight("BufferLinePickSelected", { fg = colors.amber, bg = colors.bg, style = "bold" })
set_highlight("BufferLinePickVisible", { fg = colors.amber, bg = colors.bg_dark, style = "bold" })
set_highlight("BufferLineOffsetSeparator", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("BufferLineTruncMarker", { fg = colors.amber, bg = colors.bg_dark })

-- Indent guides
set_highlight("IndentBlanklineChar", { fg = colors.gray_1 })
set_highlight("IndentBlanklineContextChar", { fg = colors.gray_3 })
set_highlight("IndentBlanklineContextStart", { sp = colors.gray_3, style = "underline" })

-- Scrollbar
set_highlight("ScrollbarHandle", { fg = colors.gray_2, bg = colors.bg_light })
set_highlight("ScrollbarSearch", { fg = colors.amber })
set_highlight("ScrollbarError", { fg = colors.red })
set_highlight("ScrollbarWarn", { fg = colors.yellow })
set_highlight("ScrollbarInfo", { fg = colors.blue })
set_highlight("ScrollbarHint", { fg = colors.sage_dim })
set_highlight("ScrollbarMisc", { fg = colors.amber_dim })
set_highlight("ScrollbarGitAdd", { fg = colors.sage })
set_highlight("ScrollbarGitChange", { fg = colors.blue })
set_highlight("ScrollbarGitDelete", { fg = colors.red })

-- Trouble
set_highlight("TroubleText", { fg = colors.fg })
set_highlight("TroubleCount", { fg = colors.amber, bg = colors.bg_light })
set_highlight("TroubleNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("TroubleLocation", { fg = colors.fg_dim })
set_highlight("TroubleFoldIcon", { fg = colors.amber })
set_highlight("TroubleIndent", { fg = colors.gray_1 })
set_highlight("TroubleFile", { fg = colors.blue, style = "bold" })
set_highlight("TroubleError", { fg = colors.red })
set_highlight("TroubleWarning", { fg = colors.yellow })
set_highlight("TroubleInformation", { fg = colors.blue })
set_highlight("TroubleHint", { fg = colors.sage_dim })
set_highlight("TroubleSource", { fg = colors.amber_dim })
set_highlight("TroubleCode", { fg = colors.sage })
set_highlight("TroubleSignError", { fg = colors.red })
set_highlight("TroubleSignWarning", { fg = colors.yellow })
set_highlight("TroubleSignInformation", { fg = colors.blue })
set_highlight("TroubleSignHint", { fg = colors.sage_dim })
set_highlight("TroubleSignOther", { fg = colors.amber })
set_highlight("TroublePreview", { bg = colors.bg_light })
set_highlight("TroubleSignCount", { fg = colors.amber, bg = colors.bg_light })

-- Aerial (outline)
set_highlight("AerialNormal", { fg = colors.fg })
set_highlight("AerialGuide", { fg = colors.gray_1 })
set_highlight("AerialLine", { bg = colors.bg_light })
set_highlight("AerialArray", { fg = colors.amber })
set_highlight("AerialBoolean", { fg = colors.amber_dim })
set_highlight("AerialClass", { fg = colors.blue })
set_highlight("AerialConstant", { fg = colors.sage })
set_highlight("AerialConstructor", { fg = colors.blue })
set_highlight("AerialEnum", { fg = colors.blue })
set_highlight("AerialEnumMember", { fg = colors.sage })
set_highlight("AerialEvent", { fg = colors.amber })
set_highlight("AerialField", { fg = colors.sage })
set_highlight("AerialFile", { fg = colors.blue })
set_highlight("AerialFunction", { fg = colors.blue })
set_highlight("AerialInterface", { fg = colors.blue })
set_highlight("AerialKey", { fg = colors.amber })
set_highlight("AerialMethod", { fg = colors.blue })
set_highlight("AerialModule", { fg = colors.blue })
set_highlight("AerialNamespace", { fg = colors.blue })
set_highlight("AerialNull", { fg = colors.amber_dim })
set_highlight("AerialNumber", { fg = colors.amber_dim })
set_highlight("AerialObject", { fg = colors.blue })
set_highlight("AerialOperator", { fg = colors.fg_dim })
set_highlight("AerialPackage", { fg = colors.blue })
set_highlight("AerialProperty", { fg = colors.sage })
set_highlight("AerialString", { fg = colors.sage })
set_highlight("AerialStruct", { fg = colors.blue })
set_highlight("AerialTypeParameter", { fg = colors.blue })
set_highlight("AerialVariable", { fg = colors.fg })

-- Navic (winbar)
set_highlight("NavicIconsFile", { fg = colors.blue })
set_highlight("NavicIconsModule", { fg = colors.blue })
set_highlight("NavicIconsNamespace", { fg = colors.blue })
set_highlight("NavicIconsPackage", { fg = colors.blue })
set_highlight("NavicIconsClass", { fg = colors.blue })
set_highlight("NavicIconsMethod", { fg = colors.blue })
set_highlight("NavicIconsProperty", { fg = colors.sage })
set_highlight("NavicIconsField", { fg = colors.sage })
set_highlight("NavicIconsConstructor", { fg = colors.blue })
set_highlight("NavicIconsEnum", { fg = colors.blue })
set_highlight("NavicIconsInterface", { fg = colors.blue })
set_highlight("NavicIconsFunction", { fg = colors.blue })
set_highlight("NavicIconsVariable", { fg = colors.fg })
set_highlight("NavicIconsConstant", { fg = colors.sage })
set_highlight("NavicIconsString", { fg = colors.sage })
set_highlight("NavicIconsNumber", { fg = colors.amber_dim })
set_highlight("NavicIconsBoolean", { fg = colors.amber_dim })
set_highlight("NavicIconsArray", { fg = colors.amber })
set_highlight("NavicIconsObject", { fg = colors.blue })
set_highlight("NavicIconsKey", { fg = colors.amber })
set_highlight("NavicIconsNull", { fg = colors.amber_dim })
set_highlight("NavicIconsEnumMember", { fg = colors.sage })
set_highlight("NavicIconsStruct", { fg = colors.blue })
set_highlight("NavicIconsEvent", { fg = colors.amber })
set_highlight("NavicIconsOperator", { fg = colors.fg_dim })
set_highlight("NavicIconsTypeParameter", { fg = colors.blue })
set_highlight("NavicText", { fg = colors.fg_dim })
set_highlight("NavicSeparator", { fg = colors.gray_3 })

-- Incline (floating statusline)
set_highlight("InclineNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("InclineNormalNC", { fg = colors.fg_dim, bg = colors.bg_dark })

-- Satellite (scroll bar)
set_highlight("SatelliteBar", { bg = colors.gray_1 })
set_highlight("SatelliteCursor", { bg = colors.gray_3 })

-- Virt-column
set_highlight("VirtColumn", { fg = colors.gray_1 })

-- Highlight-undo
set_highlight("HighlightUndo", { bg = colors.bg_light })
set_highlight("HighlightRedo", { bg = colors.bg_light })

-- Yanky
set_highlight("YankyPut", { bg = colors.bg_light })
set_highlight("YankyYanked", { bg = colors.bg_light })

-- Sneak
set_highlight("Sneak", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("SneakLabel", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("SneakScope", { bg = colors.bg_light })

-- Lightspeed
set_highlight("LightspeedLabel", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("LightspeedLabelDistant", { fg = colors.bg, bg = colors.amber_dim, style = "bold" })
set_highlight("LightspeedShortcut", { fg = colors.bg, bg = colors.red, style = "bold" })
set_highlight("LightspeedMaskedChar", { fg = colors.gray_3 })
set_highlight("LightspeedGreyWash", { fg = colors.gray_3 })
set_highlight("LightspeedUnlabeledMatch", { fg = colors.amber, style = "bold" })
set_highlight("LightspeedOneCharMatch", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("LightspeedUniqueChar", { fg = colors.amber, style = "bold" })
set_highlight("LightspeedPendingOpArea", { bg = colors.bg_light })

-- Eyeliner
set_highlight("EyelinerPrimary", { fg = colors.amber, style = "bold" })
set_highlight("EyelinerSecondary", { fg = colors.amber_dim })

-- Harpoon
set_highlight("HarpoonWindow", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("HarpoonBorder", { fg = colors.gray_1, bg = colors.bg_dark })

-- Overseer (task runner)
set_highlight("OverseerPENDING", { fg = colors.gray_3 })
set_highlight("OverseerRUNNING", { fg = colors.blue })
set_highlight("OverseerSUCCESS", { fg = colors.sage })
set_highlight("OverseerCANCELED", { fg = colors.fg_dim })
set_highlight("OverseerFAILURE", { fg = colors.red })
set_highlight("OverseerTask", { fg = colors.fg })
set_highlight("OverseerTaskBorder", { fg = colors.gray_1 })

-- Neotest
set_highlight("NeotestPassed", { fg = colors.sage })
set_highlight("NeotestFailed", { fg = colors.red })
set_highlight("NeotestRunning", { fg = colors.blue })
set_highlight("NeotestSkipped", { fg = colors.amber })
set_highlight("NeotestTest", { fg = colors.fg })
set_highlight("NeotestNamespace", { fg = colors.blue })
set_highlight("NeotestFocused", { fg = colors.amber, style = "bold" })
set_highlight("NeotestFile", { fg = colors.blue })
set_highlight("NeotestDir", { fg = colors.blue })
set_highlight("NeotestBorder", { fg = colors.gray_1 })
set_highlight("NeotestIndent", { fg = colors.gray_1 })
set_highlight("NeotestExpandMarker", { fg = colors.gray_3 })
set_highlight("NeotestAdapterName", { fg = colors.amber, style = "bold" })
set_highlight("NeotestWinSelect", { fg = colors.amber, style = "bold" })
set_highlight("NeotestMarked", { fg = colors.amber, style = "bold" })
set_highlight("NeotestTarget", { fg = colors.red, style = "bold" })
set_highlight("NeotestUnknown", { fg = colors.gray_3 })

-- DAP (debugging)
set_highlight("DapBreakpoint", { fg = colors.red })
set_highlight("DapBreakpointCondition", { fg = colors.amber })
set_highlight("DapBreakpointRejected", { fg = colors.fg_dim })
set_highlight("DapLogPoint", { fg = colors.blue })
set_highlight("DapStopped", { fg = colors.sage })
set_highlight("DapUIWatchesEmpty", { fg = colors.fg_dim })
set_highlight("DapUIWatchesValue", { fg = colors.sage })
set_highlight("DapUIWatchesError", { fg = colors.red })
set_highlight("DapUIBreakpointsPath", { fg = colors.blue })
set_highlight("DapUIBreakpointsInfo", { fg = colors.sage })
set_highlight("DapUIBreakpointsCurrentLine", { fg = colors.sage, style = "bold" })
set_highlight("DapUIBreakpointsLine", { fg = colors.gray_3 })
set_highlight("DapUIBreakpointsDisabledLine", { fg = colors.fg_dim })
set_highlight("DapUIStepOver", { fg = colors.blue })
set_highlight("DapUIStepInto", { fg = colors.blue })
set_highlight("DapUIStepBack", { fg = colors.blue })
set_highlight("DapUIStepOut", { fg = colors.blue })
set_highlight("DapUIStop", { fg = colors.red })
set_highlight("DapUIPlayPause", { fg = colors.sage })
set_highlight("DapUIRestart", { fg = colors.sage })
set_highlight("DapUIUnavailable", { fg = colors.fg_dim })
set_highlight("DapUIWinSelect", { fg = colors.amber, style = "bold" })
set_highlight("DapUINormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("DapUIVariable", { fg = colors.fg })
set_highlight("DapUIScope", { fg = colors.blue })
set_highlight("DapUIType", { fg = colors.blue })
set_highlight("DapUIValue", { fg = colors.sage })
set_highlight("DapUIModifiedValue", { fg = colors.amber, style = "bold" })
set_highlight("DapUIDecoration", { fg = colors.gray_3 })
set_highlight("DapUIThread", { fg = colors.blue })
set_highlight("DapUIStoppedThread", { fg = colors.amber })
set_highlight("DapUISource", { fg = colors.blue })
set_highlight("DapUILineNumber", { fg = colors.gray_3 })
set_highlight("DapUIFloatNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("DapUIFloatBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("DapUIFrameName", { fg = colors.fg })
set_highlight("DapUISourcePath", { fg = colors.fg_dim })
set_highlight("DapUIBreakpointsCurrentLine", { fg = colors.sage, style = "bold" })

-- Coverage
set_highlight("CoverageCovered", { fg = colors.sage })
set_highlight("CoverageUncovered", { fg = colors.red })
set_highlight("CoveragePartial", { fg = colors.amber })

-- Spectre (search and replace)
set_highlight("SpectreHeader", { fg = colors.amber, style = "bold" })
set_highlight("SpectreBody", { fg = colors.fg })
set_highlight("SpectreFile", { fg = colors.blue })
set_highlight("SpectreDir", { fg = colors.blue_dim })
set_highlight("SpectreSearch", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("SpectreBorder", { fg = colors.gray_1 })
set_highlight("SpectreReplace", { fg = colors.sage })

-- Flash
set_highlight("FlashBackdrop", { fg = colors.gray_3 })
set_highlight("FlashMatch", { fg = colors.amber, style = "bold" })
set_highlight("FlashCurrent", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("FlashLabel", { fg = colors.bg, bg = colors.red, style = "bold" })
set_highlight("FlashPrompt", { fg = colors.amber })
set_highlight("FlashPromptIcon", { fg = colors.amber })
set_highlight("FlashCursor", { fg = colors.bg, bg = colors.fg })

-- Grug-far
set_highlight("GrugFarResultsHeader", { fg = colors.amber, style = "bold" })
set_highlight("GrugFarResultsHeaderIcon", { fg = colors.amber })
set_highlight("GrugFarResultsHeaderPath", { fg = colors.blue })
set_highlight("GrugFarResultsLineNr", { fg = colors.gray_3 })
set_highlight("GrugFarResultsLineColumn", { fg = colors.gray_3 })
set_highlight("GrugFarResultsMatch", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("GrugFarResultsMatchIndicator", { fg = colors.amber })
set_highlight("GrugFarResultsChangeIndicator", { fg = colors.sage })
set_highlight("GrugFarResultsRemoveIndicator", { fg = colors.red })
set_highlight("GrugFarResultsAddedLine", { fg = colors.sage })
set_highlight("GrugFarResultsRemovedLine", { fg = colors.red })
set_highlight("GrugFarResultsFilePath", { fg = colors.blue, style = "bold" })
set_highlight("GrugFarResultsStatusSuccess", { fg = colors.sage })
set_highlight("GrugFarResultsStatusError", { fg = colors.red })
set_highlight("GrugFarResultsStatusProgress", { fg = colors.blue })
set_highlight("GrugFarInputLabel", { fg = colors.amber, style = "bold" })
set_highlight("GrugFarInputIcon", { fg = colors.amber })

-- Oil (file manager)
set_highlight("OilDir", { fg = colors.blue })
set_highlight("OilDirIcon", { fg = colors.blue })
set_highlight("OilSocket", { fg = colors.amber })
set_highlight("OilLink", { fg = colors.amber, style = "underline" })
set_highlight("OilLinkTarget", { fg = colors.amber_dim })
set_highlight("OilCopy", { fg = colors.sage })
set_highlight("OilMove", { fg = colors.blue })
set_highlight("OilChange", { fg = colors.amber })
set_highlight("OilCreate", { fg = colors.sage })
set_highlight("OilDelete", { fg = colors.red })
set_highlight("OilPermissionNone", { fg = colors.red })
set_highlight("OilPermissionRead", { fg = colors.amber })
set_highlight("OilPermissionWrite", { fg = colors.sage })
set_highlight("OilPermissionExecute", { fg = colors.blue })
set_highlight("OilPermissionDash", { fg = colors.gray_3 })
set_highlight("OilTrash", { fg = colors.red })
set_highlight("OilTrashSource", { fg = colors.fg_dim })

-- Snacks.nvim (modern UI library)
set_highlight("SnacksNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("SnacksBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("SnacksTitle", { fg = colors.amber, style = "bold" })
set_highlight("SnacksBackdrop", { bg = colors.bg_dark })
set_highlight("SnacksInput", { fg = colors.fg, bg = colors.bg_light })
set_highlight("SnacksInputBorder", { fg = colors.amber, bg = colors.bg_light })
set_highlight("SnacksInputTitle", { fg = colors.amber, style = "bold" })
set_highlight("SnacksPicker", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("SnacksPickerBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("SnacksPickerTitle", { fg = colors.amber, style = "bold" })
set_highlight("SnacksPickerMatch", { fg = colors.amber, style = "bold" })
set_highlight("SnacksPickerCursorLine", { bg = colors.bg_light })
set_highlight("SnacksPickerSelected", { fg = colors.amber })
set_highlight("SnacksPickerToggle", { fg = colors.blue })
set_highlight("SnacksPickerPrompt", { fg = colors.amber })
set_highlight("SnacksPickerDir", { fg = colors.blue })
set_highlight("SnacksPickerFile", { fg = colors.fg })
set_highlight("SnacksNotifierError", { fg = colors.red })
set_highlight("SnacksNotifierWarn", { fg = colors.yellow })
set_highlight("SnacksNotifierInfo", { fg = colors.blue })
set_highlight("SnacksNotifierDebug", { fg = colors.gray_3 })
set_highlight("SnacksNotifierTrace", { fg = colors.sage })
set_highlight("SnacksNotifierTitleError", { fg = colors.red, style = "bold" })
set_highlight("SnacksNotifierTitleWarn", { fg = colors.yellow, style = "bold" })
set_highlight("SnacksNotifierTitleInfo", { fg = colors.blue, style = "bold" })
set_highlight("SnacksNotifierTitleDebug", { fg = colors.gray_3, style = "bold" })
set_highlight("SnacksNotifierTitleTrace", { fg = colors.sage, style = "bold" })
set_highlight("SnacksNotifierBorderError", { fg = colors.red })
set_highlight("SnacksNotifierBorderWarn", { fg = colors.yellow })
set_highlight("SnacksNotifierBorderInfo", { fg = colors.blue })
set_highlight("SnacksNotifierBorderDebug", { fg = colors.gray_3 })
set_highlight("SnacksNotifierBorderTrace", { fg = colors.sage })
set_highlight("SnacksNotifierIconError", { fg = colors.red })
set_highlight("SnacksNotifierIconWarn", { fg = colors.yellow })
set_highlight("SnacksNotifierIconInfo", { fg = colors.blue })
set_highlight("SnacksNotifierIconDebug", { fg = colors.gray_3 })
set_highlight("SnacksNotifierIconTrace", { fg = colors.sage })
set_highlight("SnacksDashboardHeader", { fg = colors.amber })
set_highlight("SnacksDashboardFooter", { fg = colors.fg_dim, style = "italic" })
set_highlight("SnacksDashboardDesc", { fg = colors.fg })
set_highlight("SnacksDashboardKey", { fg = colors.amber, style = "bold" })
set_highlight("SnacksDashboardIcon", { fg = colors.sage })
set_highlight("SnacksDashboardSpecial", { fg = colors.blue })
set_highlight("SnacksIndent", { fg = colors.gray_1 })
set_highlight("SnacksIndentScope", { fg = colors.gray_3 })
set_highlight("SnacksZen", { bg = colors.bg })
set_highlight("SnacksImage", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("SnacksImageBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("SnacksImageTitle", { fg = colors.amber, style = "bold" })
set_highlight("SnacksScratch", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("SnacksScratchBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("SnacksScratchTitle", { fg = colors.amber, style = "bold" })
set_highlight("SnacksTerminal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("SnacksTerminalBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("SnacksTerminalTitle", { fg = colors.amber, style = "bold" })

-- Render-markdown
set_highlight("RenderMarkdownH1", { fg = colors.amber, style = "bold" })
set_highlight("RenderMarkdownH2", { fg = colors.amber_dim, style = "bold" })
set_highlight("RenderMarkdownH3", { fg = colors.amber_dim, style = "bold" })
set_highlight("RenderMarkdownH4", { fg = colors.amber_dim, style = "bold" })
set_highlight("RenderMarkdownH5", { fg = colors.amber_dim, style = "bold" })
set_highlight("RenderMarkdownH6", { fg = colors.amber_dim, style = "bold" })
set_highlight("RenderMarkdownH1Bg", { bg = colors.bg_light })
set_highlight("RenderMarkdownH2Bg", { bg = colors.bg_light })
set_highlight("RenderMarkdownH3Bg", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownH4Bg", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownH5Bg", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownH6Bg", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownBullet", { fg = colors.amber })
set_highlight("RenderMarkdownQuote", { fg = colors.fg_dim, style = "italic" })
set_highlight("RenderMarkdownCode", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownCodeInline", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownCodeBlock", { bg = colors.bg_highlight })
set_highlight("RenderMarkdownTableHead", { fg = colors.amber, style = "bold" })
set_highlight("RenderMarkdownTableRow", { fg = colors.fg })
set_highlight("RenderMarkdownTableFill", { fg = colors.gray_3 })
set_highlight("RenderMarkdownSuccess", { fg = colors.sage })
set_highlight("RenderMarkdownInfo", { fg = colors.blue })
set_highlight("RenderMarkdownHint", { fg = colors.sage_dim })
set_highlight("RenderMarkdownWarn", { fg = colors.yellow })
set_highlight("RenderMarkdownError", { fg = colors.red })
set_highlight("RenderMarkdownTodo", { fg = colors.amber, style = "bold" })
set_highlight("RenderMarkdownDone", { fg = colors.sage })
set_highlight("RenderMarkdownUnchecked", { fg = colors.gray_3 })
set_highlight("RenderMarkdownChecked", { fg = colors.sage })
set_highlight("RenderMarkdownLink", { fg = colors.blue, style = "underline" })
set_highlight("RenderMarkdownMath", { fg = colors.sage })

-- Blink.cmp (modern completion)
set_highlight("BlinkCmpMenu", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("BlinkCmpMenuBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("BlinkCmpMenuSelection", { fg = colors.bg, bg = colors.amber })
set_highlight("BlinkCmpScrollBarThumb", { bg = colors.gray_2 })
set_highlight("BlinkCmpScrollBarGutter", { bg = colors.bg_light })
set_highlight("BlinkCmpLabel", { fg = colors.fg })
set_highlight("BlinkCmpLabelDeprecated", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("BlinkCmpLabelMatch", { fg = colors.amber, style = "bold" })
set_highlight("BlinkCmpLabelDetail", { fg = colors.fg_dim })
set_highlight("BlinkCmpLabelDescription", { fg = colors.fg_dim })
set_highlight("BlinkCmpKind", { fg = colors.blue })
set_highlight("BlinkCmpSource", { fg = colors.fg_dim })
set_highlight("BlinkCmpGhostText", { fg = colors.gray_3 })
set_highlight("BlinkCmpDoc", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("BlinkCmpDocBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("BlinkCmpDocSeparator", { fg = colors.gray_1 })
set_highlight("BlinkCmpDocCursorLine", { bg = colors.bg_light })
set_highlight("BlinkCmpSignatureHelp", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("BlinkCmpSignatureHelpBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("BlinkCmpSignatureHelpActiveParameter", { fg = colors.amber, style = "bold" })

-- Kinds for blink
set_highlight("BlinkCmpKindText", { fg = colors.fg })
set_highlight("BlinkCmpKindMethod", { fg = colors.blue })
set_highlight("BlinkCmpKindFunction", { fg = colors.blue })
set_highlight("BlinkCmpKindConstructor", { fg = colors.blue })
set_highlight("BlinkCmpKindField", { fg = colors.sage })
set_highlight("BlinkCmpKindVariable", { fg = colors.fg })
set_highlight("BlinkCmpKindClass", { fg = colors.blue })
set_highlight("BlinkCmpKindInterface", { fg = colors.blue })
set_highlight("BlinkCmpKindModule", { fg = colors.blue })
set_highlight("BlinkCmpKindProperty", { fg = colors.sage })
set_highlight("BlinkCmpKindUnit", { fg = colors.amber_dim })
set_highlight("BlinkCmpKindValue", { fg = colors.amber_dim })
set_highlight("BlinkCmpKindEnum", { fg = colors.blue })
set_highlight("BlinkCmpKindKeyword", { fg = colors.amber })
set_highlight("BlinkCmpKindSnippet", { fg = colors.sage })
set_highlight("BlinkCmpKindColor", { fg = colors.amber })
set_highlight("BlinkCmpKindFile", { fg = colors.blue })
set_highlight("BlinkCmpKindReference", { fg = colors.amber })
set_highlight("BlinkCmpKindFolder", { fg = colors.blue })
set_highlight("BlinkCmpKindEnumMember", { fg = colors.sage })
set_highlight("BlinkCmpKindConstant", { fg = colors.sage })
set_highlight("BlinkCmpKindStruct", { fg = colors.blue })
set_highlight("BlinkCmpKindEvent", { fg = colors.amber })
set_highlight("BlinkCmpKindOperator", { fg = colors.fg_dim })
set_highlight("BlinkCmpKindTypeParameter", { fg = colors.blue })
set_highlight("BlinkCmpKindCopilot", { fg = colors.amber })
set_highlight("BlinkCmpKindCodeium", { fg = colors.sage })
set_highlight("BlinkCmpKindTabNine", { fg = colors.blue })
set_highlight("BlinkCmpKindSupermaven", { fg = colors.amber_dim })

-- Fzf-lua
set_highlight("FzfLuaNormal", { fg = colors.fg, bg = colors.bg })
set_highlight("FzfLuaBorder", { fg = colors.gray_1, bg = colors.bg })
set_highlight("FzfLuaTitle", { fg = colors.amber, style = "bold" })
set_highlight("FzfLuaPreviewNormal", { fg = colors.fg, bg = colors.bg })
set_highlight("FzfLuaPreviewBorder", { fg = colors.gray_1, bg = colors.bg })
set_highlight("FzfLuaPreviewTitle", { fg = colors.blue, style = "bold" })
set_highlight("FzfLuaCursor", { fg = colors.bg, bg = colors.fg })
set_highlight("FzfLuaCursorLine", { bg = colors.bg_light })
set_highlight("FzfLuaCursorLineNr", { fg = colors.amber, bg = colors.bg_light })
set_highlight("FzfLuaSearch", { fg = colors.bg, bg = colors.amber })
set_highlight("FzfLuaScrollBorderEmpty", { fg = colors.gray_1 })
set_highlight("FzfLuaScrollBorderFull", { fg = colors.amber })
set_highlight("FzfLuaScrollFloatEmpty", { bg = colors.bg_light })
set_highlight("FzfLuaScrollFloatFull", { bg = colors.gray_2 })
set_highlight("FzfLuaHelpNormal", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("FzfLuaHelpBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("FzfLuaHeaderBind", { fg = colors.amber })
set_highlight("FzfLuaHeaderText", { fg = colors.fg })
set_highlight("FzfLuaPathColNr", { fg = colors.amber_dim })
set_highlight("FzfLuaPathLineNr", { fg = colors.sage })
set_highlight("FzfLuaBufName", { fg = colors.blue })
set_highlight("FzfLuaBufNr", { fg = colors.amber_dim })
set_highlight("FzfLuaBufFlagCur", { fg = colors.red })
set_highlight("FzfLuaBufFlagAlt", { fg = colors.amber })
set_highlight("FzfLuaTabTitle", { fg = colors.amber, style = "bold" })
set_highlight("FzfLuaTabMarker", { fg = colors.red, style = "bold" })
set_highlight("FzfLuaDirIcon", { fg = colors.blue })
set_highlight("FzfLuaDirPart", { fg = colors.blue_dim })
set_highlight("FzfLuaFilePart", { fg = colors.fg })
set_highlight("FzfLuaLiveSym", { fg = colors.amber })
set_highlight("FzfLuaFzfNormal", { fg = colors.fg })
set_highlight("FzfLuaFzfCursorLine", { bg = colors.bg_light })
set_highlight("FzfLuaFzfMatch", { fg = colors.amber, style = "bold" })
set_highlight("FzfLuaFzfBorder", { fg = colors.gray_1 })
set_highlight("FzfLuaFzfScrollbar", { fg = colors.gray_2 })
set_highlight("FzfLuaFzfSeparator", { fg = colors.gray_3 })
set_highlight("FzfLuaFzfGutter", { bg = colors.bg_dark })
set_highlight("FzfLuaFzfHeader", { fg = colors.amber })
set_highlight("FzfLuaFzfInfo", { fg = colors.blue })
set_highlight("FzfLuaFzfPointer", { fg = colors.amber })
set_highlight("FzfLuaFzfMarker", { fg = colors.red })
set_highlight("FzfLuaFzfSpinner", { fg = colors.blue })
set_highlight("FzfLuaFzfPrompt", { fg = colors.amber })
set_highlight("FzfLuaFzfQuery", { fg = colors.fg, style = "bold" })

-- CodeCompanion (AI assistant)
set_highlight("CodeCompanionChatHeader", { fg = colors.amber, style = "bold" })
set_highlight("CodeCompanionChatSeparator", { fg = colors.gray_1 })
set_highlight("CodeCompanionChatMessage", { fg = colors.fg })
set_highlight("CodeCompanionChatTool", { fg = colors.blue, style = "bold" })
set_highlight("CodeCompanionChatVariable", { fg = colors.sage, style = "bold" })
set_highlight("CodeCompanionChatAvatar", { fg = colors.amber })
set_highlight("CodeCompanionChatRole", { fg = colors.amber, style = "bold" })
set_highlight("CodeCompanionChatBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("CodeCompanionChatNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("CodeCompanionChatDiffAdd", { fg = colors.sage })
set_highlight("CodeCompanionChatDiffDelete", { fg = colors.red })
set_highlight("CodeCompanionVirtualText", { fg = colors.fg_dim, style = "italic" })
set_highlight("CodeCompanionSuggestion", { fg = colors.gray_3 })
set_highlight("CodeCompanionCurrentLine", { bg = colors.bg_light })

-- Avante (AI assistant)
set_highlight("AvanteTitle", { fg = colors.amber, style = "bold" })
set_highlight("AvanteSubtitle", { fg = colors.blue, style = "bold" })
set_highlight("AvanteThirdTitle", { fg = colors.sage, style = "bold" })
set_highlight("AvanteReversedTitle", { fg = colors.bg, bg = colors.amber, style = "bold" })
set_highlight("AvanteReversedSubtitle", { fg = colors.bg, bg = colors.blue, style = "bold" })
set_highlight("AvanteReversedThirdTitle", { fg = colors.bg, bg = colors.sage, style = "bold" })
set_highlight("AvantePrompt", { fg = colors.fg, bg = colors.bg_light })
set_highlight("AvanteCodeBlock", { bg = colors.bg_highlight })
set_highlight("AvanteInlineCode", { bg = colors.bg_highlight })
set_highlight("AvanteConflictCurrent", { bg = "#1f2a1f" })
set_highlight("AvanteConflictCurrentLabel", { fg = colors.sage, style = "bold" })
set_highlight("AvanteConflictIncoming", { bg = "#1f252a" })
set_highlight("AvanteConflictIncomingLabel", { fg = colors.blue, style = "bold" })
set_highlight("AvantePopupHint", { fg = colors.fg_dim, style = "italic" })

-- Ollama (AI)
set_highlight("OllamaPrompt", { fg = colors.amber, style = "bold" })
set_highlight("OllamaResponse", { fg = colors.fg })
set_highlight("OllamaSeparator", { fg = colors.gray_1 })

-- CopilotChat
set_highlight("CopilotChatHeader", { fg = colors.amber, style = "bold" })
set_highlight("CopilotChatSeparator", { fg = colors.gray_1 })
set_highlight("CopilotChatMe", { fg = colors.blue })
set_highlight("CopilotChatCopilot", { fg = colors.amber })
set_highlight("CopilotChatSystem", { fg = colors.sage })

-- ChatGPT
set_highlight("ChatGPTQuestion", { fg = colors.blue, style = "bold" })
set_highlight("ChatGPTAnswer", { fg = colors.fg })
set_highlight("ChatGPTTotalTokens", { fg = colors.fg_dim })
set_highlight("ChatGPTTotalTokensBorder", { fg = colors.gray_1 })
set_highlight("ChatGPTWelcome", { fg = colors.amber, style = "bold" })

-- Grammarous
set_highlight("GrammarousError", { sp = colors.red, style = "undercurl" })
set_highlight("GrammarousWarning", { sp = colors.yellow, style = "undercurl" })

-- Headlines (markdown)
set_highlight("Headline1", { bg = colors.bg_light })
set_highlight("Headline2", { bg = colors.bg_highlight })
set_highlight("Headline3", { bg = colors.bg_highlight })
set_highlight("Headline4", { bg = colors.bg_highlight })
set_highlight("Headline5", { bg = colors.bg_highlight })
set_highlight("Headline6", { bg = colors.bg_highlight })
set_highlight("CodeBlock", { bg = colors.bg_highlight })
set_highlight("Dash", { fg = colors.gray_1 })

-- Orgmode
set_highlight("OrgTodo", { fg = colors.red, style = "bold" })
set_highlight("OrgDone", { fg = colors.sage, style = "bold" })
set_highlight("OrgDeadline", { fg = colors.red })
set_highlight("OrgScheduled", { fg = colors.blue })
set_highlight("OrgScheduledToday", { fg = colors.amber })
set_highlight("OrgAgendaDone", { fg = colors.sage })
set_highlight("OrgAgendaDeadline", { fg = colors.red })
set_highlight("OrgAgendaScheduled", { fg = colors.blue })
set_highlight("OrgAgendaScheduledPast", { fg = colors.amber_dim })
set_highlight("OrgTimeStamp", { fg = colors.amber })
set_highlight("OrgTimeStampActive", { fg = colors.amber, style = "bold" })
set_highlight("OrgTimeStampInactive", { fg = colors.fg_dim })
set_highlight("OrgPriorityA", { fg = colors.red, style = "bold" })
set_highlight("OrgPriorityB", { fg = colors.amber, style = "bold" })
set_highlight("OrgPriorityC", { fg = colors.blue, style = "bold" })
set_highlight("OrgTag", { fg = colors.sage })
set_highlight("OrgTagSpecial", { fg = colors.amber })
set_highlight("OrgBlock", { bg = colors.bg_highlight })
set_highlight("OrgBlockBeginLine", { fg = colors.fg_dim, style = "italic" })
set_highlight("OrgBlockEndLine", { fg = colors.fg_dim, style = "italic" })
set_highlight("OrgPropertyDrawer", { fg = colors.fg_dim })
set_highlight("OrgDrawer", { fg = colors.fg_dim })
set_highlight("OrgMetaLine", { fg = colors.fg_dim, style = "italic" })
set_highlight("OrgComment", { fg = colors.fg_dim, style = "italic" })
set_highlight("OrgHeadlineLevel1", { fg = colors.amber, style = "bold" })
set_highlight("OrgHeadlineLevel2", { fg = colors.amber_dim, style = "bold" })
set_highlight("OrgHeadlineLevel3", { fg = colors.blue, style = "bold" })
set_highlight("OrgHeadlineLevel4", { fg = colors.blue_dim, style = "bold" })
set_highlight("OrgHeadlineLevel5", { fg = colors.sage, style = "bold" })
set_highlight("OrgHeadlineLevel6", { fg = colors.sage_dim, style = "bold" })
set_highlight("OrgHeadlineLevel7", { fg = colors.fg, style = "bold" })
set_highlight("OrgHeadlineLevel8", { fg = colors.fg_dim, style = "bold" })

-- Neorg
set_highlight("NeorgHeading1Title", { fg = colors.amber, style = "bold" })
set_highlight("NeorgHeading1Prefix", { fg = colors.amber, style = "bold" })
set_highlight("NeorgHeading2Title", { fg = colors.amber_dim, style = "bold" })
set_highlight("NeorgHeading2Prefix", { fg = colors.amber_dim, style = "bold" })
set_highlight("NeorgHeading3Title", { fg = colors.blue, style = "bold" })
set_highlight("NeorgHeading3Prefix", { fg = colors.blue, style = "bold" })
set_highlight("NeorgHeading4Title", { fg = colors.blue_dim, style = "bold" })
set_highlight("NeorgHeading4Prefix", { fg = colors.blue_dim, style = "bold" })
set_highlight("NeorgHeading5Title", { fg = colors.sage, style = "bold" })
set_highlight("NeorgHeading5Prefix", { fg = colors.sage, style = "bold" })
set_highlight("NeorgHeading6Title", { fg = colors.sage_dim, style = "bold" })
set_highlight("NeorgHeading6Prefix", { fg = colors.sage_dim, style = "bold" })
set_highlight("NeorgMarkerTitle", { fg = colors.amber, style = "bold" })
set_highlight("NeorgMarker", { fg = colors.amber })
set_highlight("NeorgQuote", { fg = colors.fg_dim, style = "italic" })
set_highlight("NeorgQuoteContent", { fg = colors.fg_dim })
set_highlight("NeorgTodoItem1", { fg = colors.red })
set_highlight("NeorgTodoItem2", { fg = colors.amber })
set_highlight("NeorgTodoItem3", { fg = colors.blue })
set_highlight("NeorgTodoItem4", { fg = colors.sage })
set_highlight("NeorgTodoItem5", { fg = colors.fg })
set_highlight("NeorgTodoDone", { fg = colors.sage })
set_highlight("NeorgTodoPending", { fg = colors.amber })
set_highlight("NeorgTodoUndone", { fg = colors.red })
set_highlight("NeorgTodoHold", { fg = colors.blue })
set_highlight("NeorgTodoCancelled", { fg = colors.fg_dim })
set_highlight("NeorgTodoRecurring", { fg = colors.sage })
set_highlight("NeorgTodoImportant", { fg = colors.red, style = "bold" })
set_highlight("NeorgTodoOnHold", { fg = colors.blue })
set_highlight("NeorgTodoInProgress", { fg = colors.amber })
set_highlight("NeorgTodoUncertain", { fg = colors.yellow })
set_highlight("NeorgTodoUrgent", { fg = colors.red, style = "bold" })
set_highlight("NeorgTodoTrivial", { fg = colors.fg_dim })
set_highlight("NeorgListItem", { fg = colors.amber })
set_highlight("NeorgListItem1", { fg = colors.amber })
set_highlight("NeorgListItem2", { fg = colors.amber_dim })
set_highlight("NeorgListItem3", { fg = colors.blue })
set_highlight("NeorgListItem4", { fg = colors.sage })
set_highlight("NeorgListItem5", { fg = colors.fg })
set_highlight("NeorgListItem6", { fg = colors.fg_dim })
set_highlight("NeorgTag", { fg = colors.sage })
set_highlight("NeorgTagContent", { fg = colors.fg })
set_highlight("NeorgTagContentDelimiter", { fg = colors.gray_3 })
set_highlight("NeorgTagDelimiter", { fg = colors.gray_3 })
set_highlight("NeorgTagName", { fg = colors.amber })
set_highlight("NeorgTagNameWord", { fg = colors.amber })
set_highlight("NeorgTagParameter", { fg = colors.blue })
set_highlight("NeorgTagParameterValue", { fg = colors.sage })
set_highlight("NeorgDefinitionTitle", { fg = colors.amber, style = "bold" })
set_highlight("NeorgDefinitionContent", { fg = colors.fg })
set_highlight("NeorgFootnote", { fg = colors.amber_dim })
set_highlight("NeorgFootnoteContent", { fg = colors.fg_dim })
set_highlight("NeorgLinkFile", { fg = colors.blue, style = "underline" })
set_highlight("NeorgLinkText", { fg = colors.blue, style = "underline" })
set_highlight("NeorgLinkDescription", { fg = colors.fg_dim })
set_highlight("NeorgLinkLocationExternal", { fg = colors.sage })
set_highlight("NeorgLinkLocationGeneric", { fg = colors.fg })
set_highlight("NeorgLinkLocationInternal", { fg = colors.amber })
set_highlight("NeorgLinkLocationMarker", { fg = colors.amber_dim })
set_highlight("NeorgLinkLocationUrl", { fg = colors.blue, style = "underline" })
set_highlight("NeorgLinkLocationWiki", { fg = colors.amber })
set_highlight("NeorgAnchor", { fg = colors.amber })
set_highlight("NeorgAnchorDeclaration", { fg = colors.amber })
set_highlight("NeorgAnchorDefinition", { fg = colors.amber_dim })
set_highlight("NeorgAnchorFile", { fg = colors.blue })
set_highlight("NeorgAnchorObject", { fg = colors.sage })
set_highlight("NeorgCarryover", { fg = colors.fg_dim })
set_highlight("NeorgCarryoverTag", { fg = colors.amber })
set_highlight("NeorgCarryoverTagName", { fg = colors.amber })
set_highlight("NeorgCarryoverTagParameter", { fg = colors.blue })
set_highlight("NeorgDetachedModifier", { fg = colors.amber })
set_highlight("NeorgWeakParagraphPrefix", { fg = colors.fg_dim })
set_highlight("NeorgStrongParagraphPrefix", { fg = colors.amber })
set_highlight("NeorgSelectionWindow", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("NeorgSelectionWindowKey", { fg = colors.amber, style = "bold" })
set_highlight("NeorgSelectionWindowKeyname", { fg = colors.blue })
set_highlight("NeorgSelectionWindowNamespace", { fg = colors.sage })
set_highlight("NeorgSelectionWindowSlash", { fg = colors.gray_3 })
set_highlight("NeorgSelectionWindowBrackets", { fg = colors.gray_3 })
set_highlight("NeorgSelectionWindowFile", { fg = colors.fg })
set_highlight("NeorgSelectionWindowBackspace", { fg = colors.red })
set_highlight("NeorgSelectionWindowArrow", { fg = colors.amber })
set_highlight("NeorgSelectionWindowPrompt", { fg = colors.amber, style = "bold" })

-- Obsidian
set_highlight("ObsidianTodo", { fg = colors.amber, style = "bold" })
set_highlight("ObsidianDone", { fg = colors.sage, style = "bold" })
set_highlight("ObsidianProgress", { fg = colors.blue })
set_highlight("ObsidianImportant", { fg = colors.red, style = "bold" })
set_highlight("ObsidianBullet", { fg = colors.amber })
set_highlight("ObsidianRefText", { fg = colors.blue, style = "underline" })
set_highlight("ObsidianExtLinkIcon", { fg = colors.blue })
set_highlight("ObsidianTag", { fg = colors.sage })
set_highlight("ObsidianBlockID", { fg = colors.amber_dim })
set_highlight("ObsidianHighlightText", { bg = colors.bg_light })
set_highlight("ObsidianRightArrow", { fg = colors.amber })
set_highlight("ObsidianTilde", { fg = colors.red })

-- Vimwiki
set_highlight("VimwikiHeader1", { fg = colors.amber, style = "bold" })
set_highlight("VimwikiHeader2", { fg = colors.amber_dim, style = "bold" })
set_highlight("VimwikiHeader3", { fg = colors.blue, style = "bold" })
set_highlight("VimwikiHeader4", { fg = colors.blue_dim, style = "bold" })
set_highlight("VimwikiHeader5", { fg = colors.sage, style = "bold" })
set_highlight("VimwikiHeader6", { fg = colors.sage_dim, style = "bold" })
set_highlight("VimwikiLink", { fg = colors.blue, style = "underline" })
set_highlight("VimwikiListTodo", { fg = colors.amber })
set_highlight("VimwikiTag", { fg = colors.sage })
set_highlight("VimwikiCode", { bg = colors.bg_highlight })
set_highlight("VimwikiBold", { style = "bold" })
set_highlight("VimwikiItalic", { style = "italic" })
set_highlight("VimwikiBoldItalic", { style = "bold,italic" })
set_highlight("VimwikiUnderline", { style = "underline" })
set_highlight("VimwikiDelText", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("VimwikiSuperScript", { fg = colors.amber_dim })
set_highlight("VimwikiSubScript", { fg = colors.amber_dim })
set_highlight("VimwikiCheckBoxDone", { fg = colors.sage })

-- Telekasten
set_highlight("TelekastenTitle", { fg = colors.amber, style = "bold" })
set_highlight("TelekastenHighlight", { bg = colors.bg_light })
set_highlight("TelekastenCalendarToday", { fg = colors.amber, style = "bold" })
set_highlight("TelekastenCalendarPast", { fg = colors.fg_dim })
set_highlight("TelekastenCalendarFuture", { fg = colors.blue })
set_highlight("TelekastenLink", { fg = colors.blue, style = "underline" })
set_highlight("TelekastenTag", { fg = colors.sage })
set_highlight("TelekastenHeading", { fg = colors.amber, style = "bold" })

-- Zk (zettelkasten)
set_highlight("ZkBacklinksTitle", { fg = colors.amber, style = "bold" })
set_highlight("ZkBacklinkMatch", { fg = colors.amber, style = "bold" })
set_highlight("ZkBacklinkContext", { fg = colors.fg_dim })
set_highlight("ZkBacklinkPath", { fg = colors.blue })
set_highlight("ZkBacklinkLineNr", { fg = colors.gray_3 })
set_highlight("ZkOrphansTitle", { fg = colors.amber, style = "bold" })
set_highlight("ZkOrphanMatch", { fg = colors.amber, style = "bold" })
set_highlight("ZkOrphanContext", { fg = colors.fg_dim })
set_highlight("ZkOrphanPath", { fg = colors.blue })
set_highlight("ZkOrphanLineNr", { fg = colors.gray_3 })
set_highlight("ZkLinksTitle", { fg = colors.amber, style = "bold" })
set_highlight("ZkLinkMatch", { fg = colors.amber, style = "bold" })
set_highlight("ZkLinkContext", { fg = colors.fg_dim })
set_highlight("ZkLinkPath", { fg = colors.blue })
set_highlight("ZkLinkLineNr", { fg = colors.gray_3 })
set_highlight("ZkTagsTitle", { fg = colors.amber, style = "bold" })
set_highlight("ZkTagMatch", { fg = colors.sage, style = "bold" })
set_highlight("ZkTagContext", { fg = colors.fg_dim })
set_highlight("ZkTagPath", { fg = colors.blue })
set_highlight("ZkTagLineNr", { fg = colors.gray_3 })

-- Neogit
set_highlight("NeogitBranch", { fg = colors.amber, style = "bold" })
set_highlight("NeogitRemote", { fg = colors.blue, style = "bold" })
set_highlight("NeogitObjectId", { fg = colors.fg_dim })
set_highlight("NeogitStash", { fg = colors.fg_dim })
set_highlight("NeogitFold", { fg = colors.gray_3 })
set_highlight("NeogitRebaseDone", { fg = colors.sage })
set_highlight("NeogitRebaseTodo", { fg = colors.amber })
set_highlight("NeogitRebaseProgress", { fg = colors.blue })
set_highlight("NeogitRebasePick", { fg = colors.fg })
set_highlight("NeogitRebaseReword", { fg = colors.amber })
set_highlight("NeogitRebaseExec", { fg = colors.blue })
set_highlight("NeogitRebaseDrop", { fg = colors.red })
set_highlight("NeogitRebaseSquash", { fg = colors.sage })
set_highlight("NeogitRebaseFixup", { fg = colors.amber_dim })
set_highlight("NeogitHunkHeader", { fg = colors.fg, bg = colors.bg_light })
set_highlight("NeogitHunkHeaderHighlight", { fg = colors.amber, bg = colors.bg_light, style = "bold" })
set_highlight("NeogitDiffContext", { bg = colors.bg })
set_highlight("NeogitDiffContextHighlight", { bg = colors.bg_highlight })
set_highlight("NeogitDiffAdd", { fg = colors.sage, bg = "#1f2a1f" })
set_highlight("NeogitDiffAddHighlight", { fg = colors.sage, bg = "#2a3a2a" })
set_highlight("NeogitDiffDelete", { fg = colors.red, bg = "#2a1f1f" })
set_highlight("NeogitDiffDeleteHighlight", { fg = colors.red, bg = "#3a2a2a" })
set_highlight("NeogitDiffHeader", { fg = colors.blue, bg = colors.bg_light })
set_highlight("NeogitDiffHeaderHighlight", { fg = colors.blue, style = "bold" })
set_highlight("NeogitSectionHeader", { fg = colors.amber, style = "bold" })
set_highlight("NeogitUnmergedInto", { fg = colors.amber })
set_highlight("NeogitUnpushedTo", { fg = colors.blue })
set_highlight("NeogitUnpulledFrom", { fg = colors.sage })
set_highlight("NeogitChangeModified", { fg = colors.blue, style = "bold" })
set_highlight("NeogitChangeAdded", { fg = colors.sage, style = "bold" })
set_highlight("NeogitChangeDeleted", { fg = colors.red, style = "bold" })
set_highlight("NeogitChangeRenamed", { fg = colors.amber, style = "bold" })
set_highlight("NeogitChangeUpdated", { fg = colors.blue, style = "bold" })
set_highlight("NeogitChangeCopied", { fg = colors.amber_dim, style = "bold" })
set_highlight("NeogitChangeUnmerged", { fg = colors.red, style = "bold" })
set_highlight("NeogitChangeNewFile", { fg = colors.sage, style = "bold" })
set_highlight("NeogitChangeConflict", { fg = colors.red, style = "bold" })
set_highlight("NeogitNotificationInfo", { fg = colors.blue })
set_highlight("NeogitNotificationWarning", { fg = colors.yellow })
set_highlight("NeogitNotificationError", { fg = colors.red })
set_highlight("NeogitCommandText", { fg = colors.fg })
set_highlight("NeogitCommandTime", { fg = colors.amber_dim })
set_highlight("NeogitCommandCodeNormal", { fg = colors.sage })
set_highlight("NeogitCommandCodeError", { fg = colors.red })
set_highlight("NeogitPopupSectionTitle", { fg = colors.amber, style = "bold" })
set_highlight("NeogitPopupBranchName", { fg = colors.amber })
set_highlight("NeogitPopupBold", { style = "bold" })
set_highlight("NeogitPopupSwitchKey", { fg = colors.amber })
set_highlight("NeogitPopupSwitchEnabled", { fg = colors.sage })
set_highlight("NeogitPopupSwitchDisabled", { fg = colors.fg_dim })
set_highlight("NeogitPopupOptionKey", { fg = colors.blue })
set_highlight("NeogitPopupOptionEnabled", { fg = colors.sage })
set_highlight("NeogitPopupOptionDisabled", { fg = colors.fg_dim })
set_highlight("NeogitPopupConfigKey", { fg = colors.amber_dim })
set_highlight("NeogitPopupConfigEnabled", { fg = colors.sage })
set_highlight("NeogitPopupConfigDisabled", { fg = colors.fg_dim })
set_highlight("NeogitPopupActionKey", { fg = colors.amber })
set_highlight("NeogitPopupActionDisabled", { fg = colors.fg_dim })

-- Diffview
set_highlight("DiffviewFilePanelTitle", { fg = colors.amber, style = "bold" })
set_highlight("DiffviewFilePanelCounter", { fg = colors.amber, style = "bold" })
set_highlight("DiffviewFilePanelFileName", { fg = colors.fg })
set_highlight("DiffviewFilePanelPath", { fg = colors.fg_dim })
set_highlight("DiffviewFilePanelInsertions", { fg = colors.sage })
set_highlight("DiffviewFilePanelDeletions", { fg = colors.red })
set_highlight("DiffviewFilePanelRootPath", { fg = colors.blue, style = "bold" })
set_highlight("DiffviewStatusAdded", { fg = colors.sage })
set_highlight("DiffviewStatusUntracked", { fg = colors.sage })
set_highlight("DiffviewStatusModified", { fg = colors.blue })
set_highlight("DiffviewStatusRenamed", { fg = colors.amber })
set_highlight("DiffviewStatusCopied", { fg = colors.amber_dim })
set_highlight("DiffviewStatusTypeChange", { fg = colors.blue })
set_highlight("DiffviewStatusUnmerged", { fg = colors.red })
set_highlight("DiffviewStatusUnknown", { fg = colors.red })
set_highlight("DiffviewStatusDeleted", { fg = colors.red })
set_highlight("DiffviewStatusBroken", { fg = colors.red })
set_highlight("DiffviewStatusIgnored", { fg = colors.fg_dim })
set_highlight("DiffviewFolderSign", { fg = colors.blue })
set_highlight("DiffviewFolderName", { fg = colors.blue })
set_highlight("DiffviewFolderOpen", { fg = colors.blue })
set_highlight("DiffviewFolderClosed", { fg = colors.blue })
set_highlight("DiffviewHash", { fg = colors.amber_dim })
set_highlight("DiffviewReference", { fg = colors.amber, style = "bold" })
set_highlight("DiffviewReflogHead", { fg = colors.amber, style = "bold" })
set_highlight("DiffviewReflogRemote", { fg = colors.blue })
set_highlight("DiffviewReflogStash", { fg = colors.sage })
set_highlight("DiffviewReflogOther", { fg = colors.fg_dim })

-- Gitsigns
set_highlight("GitSignsAdd", { fg = colors.sage })
set_highlight("GitSignsChange", { fg = colors.blue })
set_highlight("GitSignsDelete", { fg = colors.red })
set_highlight("GitSignsAddNr", { fg = colors.sage })
set_highlight("GitSignsChangeNr", { fg = colors.blue })
set_highlight("GitSignsDeleteNr", { fg = colors.red })
set_highlight("GitSignsAddLn", { bg = "#1f2a1f" })
set_highlight("GitSignsChangeLn", { bg = "#1f252a" })
set_highlight("GitSignsDeleteLn", { bg = "#2a1f1f" })
set_highlight("GitSignsAddPreview", { fg = colors.sage, bg = "#1f2a1f" })
set_highlight("GitSignsDeletePreview", { fg = colors.red, bg = "#2a1f1f" })
set_highlight("GitSignsCurrentLineBlame", { fg = colors.fg_dim, style = "italic" })
set_highlight("GitSignsAddInline", { fg = colors.bg, bg = colors.sage })
set_highlight("GitSignsDeleteInline", { fg = colors.bg, bg = colors.red })
set_highlight("GitSignsChangeInline", { fg = colors.bg, bg = colors.blue })
set_highlight("GitSignsAddLnInline", { fg = colors.bg, bg = colors.sage })
set_highlight("GitSignsChangeLnInline", { fg = colors.bg, bg = colors.blue })
set_highlight("GitSignsDeleteLnInline", { fg = colors.bg, bg = colors.red })
set_highlight("GitSignsDeleteVirtLn", { fg = colors.red, bg = "#2a1f1f" })
set_highlight("GitSignsDeleteVirtLnInLine", { fg = colors.bg, bg = colors.red })
set_highlight("GitSignsVirtLnum", { fg = colors.red })

-- Git-conflict
set_highlight("GitConflictCurrent", { bg = "#1f2a1f" })
set_highlight("GitConflictIncoming", { bg = "#1f252a" })
set_highlight("GitConflictAncestor", { bg = "#2a2520" })
set_highlight("GitConflictCurrentLabel", { fg = colors.sage, style = "bold" })
set_highlight("GitConflictIncomingLabel", { fg = colors.blue, style = "bold" })
set_highlight("GitConflictAncestorLabel", { fg = colors.amber, style = "bold" })
set_highlight("GitConflictCurrentMark", { fg = colors.sage })
set_highlight("GitConflictIncomingMark", { fg = colors.blue })
set_highlight("GitConflictAncestorMark", { fg = colors.amber })

-- Octo (github)
set_highlight("OctoGreen", { fg = colors.sage })
set_highlight("OctoRed", { fg = colors.red })
set_highlight("OctoPurple", { fg = colors.amber_dim })
set_highlight("OctoYellow", { fg = colors.yellow })
set_highlight("OctoBlue", { fg = colors.blue })
set_highlight("OctoGrey", { fg = colors.fg_dim })
set_highlight("OctoBubble", { fg = colors.bg, bg = colors.fg_dim })
set_highlight("OctoBubbleGreen", { fg = colors.bg, bg = colors.sage })
set_highlight("OctoBubbleRed", { fg = colors.bg, bg = colors.red })
set_highlight("OctoBubblePurple", { fg = colors.bg, bg = colors.amber_dim })
set_highlight("OctoBubbleYellow", { fg = colors.bg, bg = colors.yellow })
set_highlight("OctoBubbleBlue", { fg = colors.bg, bg = colors.blue })
set_highlight("OctoWhite", { fg = colors.fg })
set_highlight("OctoDirty", { fg = colors.amber })
set_highlight("OctoIssueId", { fg = colors.fg_dim })
set_highlight("OctoIssueTitle", { fg = colors.fg, style = "bold" })
set_highlight("OctoStateOpen", { fg = colors.sage })
set_highlight("OctoStateClosed", { fg = colors.red })
set_highlight("OctoStateMerged", { fg = colors.amber_dim })
set_highlight("OctoStatePending", { fg = colors.yellow })
set_highlight("OctoLabel", { fg = colors.amber })
set_highlight("OctoReaction", { fg = colors.amber })
set_highlight("OctoReactionViewer", { fg = colors.amber, style = "bold" })
set_highlight("OctoPassingTest", { fg = colors.sage })
set_highlight("OctoFailingTest", { fg = colors.red })
set_highlight("OctoPendingTest", { fg = colors.yellow })
set_highlight("OctoUser", { fg = colors.blue, style = "bold" })
set_highlight("OctoUserViewer", { fg = colors.amber, style = "bold" })
set_highlight("OctoMention", { fg = colors.amber })
set_highlight("OctoDetailsLabel", { fg = colors.amber, style = "bold" })
set_highlight("OctoDetailsValue", { fg = colors.fg })
set_highlight("OctoMissingDetails", { fg = colors.fg_dim })
set_highlight("OctoFloat", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("OctoFloatBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("OctoFloatHeading", { fg = colors.amber, style = "bold" })
set_highlight("OctoViewer", { fg = colors.amber })
set_highlight("OctoCommentLine", { fg = colors.fg_dim })
set_highlight("OctoCommentLineViewer", { fg = colors.amber })
set_highlight("OctoTimelineMarker", { fg = colors.amber })
set_highlight("OctoTimelineItemHeading", { fg = colors.amber, style = "bold" })
set_highlight("OctoSymbol", { fg = colors.blue })
set_highlight("OctoDate", { fg = colors.fg_dim })
set_highlight("OctoDetailsBlock", { bg = colors.bg_highlight })
set_highlight("OctoNormal", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("OctoStatusColumn", { fg = colors.fg_dim })
set_highlight("OctoStatusLine", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("OctoStatusLineNC", { fg = colors.fg_dim, bg = colors.bg_dark })
set_highlight("OctoStatusLineSeparator", { fg = colors.gray_1 })
set_highlight("OctoSignColumn", { bg = colors.bg })
set_highlight("OctoFilePanelFileName", { fg = colors.fg })
set_highlight("OctoFilePanelPath", { fg = colors.fg_dim })

-- Fugitive
set_highlight("fugitiveHash", { fg = colors.amber_dim })
set_highlight("fugitiveSymbolicRef", { fg = colors.amber, style = "bold" })
set_highlight("fugitiveUntrackedHeading", { fg = colors.sage, style = "bold" })
set_highlight("fugitiveUnstagedHeading", { fg = colors.blue, style = "bold" })
set_highlight("fugitiveStagedHeading", { fg = colors.amber, style = "bold" })
set_highlight("fugitiveHeading", { fg = colors.amber, style = "bold" })
set_highlight("fugitiveHelpTag", { fg = colors.amber })
set_highlight("fugitiveHelpHeader", { fg = colors.amber, style = "bold" })
set_highlight("fugitiveCount", { fg = colors.amber, style = "bold" })
set_highlight("fugitiveHeader", { fg = colors.amber, style = "bold" })

-- Rhubarb
set_highlight("RhubarbSymbol", { fg = colors.blue })
set_highlight("RhubarbObject", { fg = colors.amber })

-- Git-messenger
set_highlight("gitmessengerHeader", { fg = colors.amber, style = "bold" })
set_highlight("gitmessengerHash", { fg = colors.amber_dim })
set_highlight("gitmessengerHistory", { fg = colors.blue })
set_highlight("gitmessengerEmail", { fg = colors.sage })
set_highlight("gitmessengerDate", { fg = colors.fg_dim })

-- VGit
set_highlight("VGitSignAdd", { fg = colors.sage })
set_highlight("VGitSignRemove", { fg = colors.red })
set_highlight("VGitSignChange", { fg = colors.blue })
set_highlight("VGitSignUntrack", { fg = colors.fg_dim })
set_highlight("VGitIndicator", { fg = colors.amber })
set_highlight("VGitBorder", { fg = colors.gray_1 })
set_highlight("VGitBorderFocus", { fg = colors.amber })
set_highlight("VGitTitle", { fg = colors.amber, style = "bold" })
set_highlight("VGitHeading", { fg = colors.amber, style = "bold" })
set_highlight("VGitSelected", { bg = colors.bg_light })
set_highlight("VGitBackground", { bg = colors.bg_dark })
set_highlight("VGitText", { fg = colors.fg })
set_highlight("VGitComment", { fg = colors.fg_dim })
set_highlight("VGitLineNumber", { fg = colors.gray_3 })
set_highlight("VGitAuthor", { fg = colors.blue })
set_highlight("VGitCommittedOn", { fg = colors.fg_dim })
set_highlight("VGitCommitBody", { fg = colors.fg })
set_highlight("VGitCommitOverflow", { fg = colors.red })
set_highlight("VGitCommitSummary", { fg = colors.amber, style = "bold" })
set_highlight("VGitCommitBlank", { fg = colors.fg_dim })
set_highlight("VGitDiffAddSign", { fg = colors.sage })
set_highlight("VGitDiffRemoveSign", { fg = colors.red })
set_highlight("VGitDiffChangeSign", { fg = colors.blue })
set_highlight("VGitDiffText", { fg = colors.fg })
set_highlight("VGitDiffAddText", { fg = colors.sage })
set_highlight("VGitDiffRemoveText", { fg = colors.red })
set_highlight("VGitDiffChangeText", { fg = colors.blue })
set_highlight("VGitDiffAddSignColumn", { bg = "#1f2a1f" })
set_highlight("VGitDiffRemoveSignColumn", { bg = "#2a1f1f" })
set_highlight("VGitDiffChangeSignColumn", { bg = "#1f252a" })
set_highlight("VGitHunkAdd", { bg = "#1f2a1f" })
set_highlight("VGitHunkRemove", { bg = "#2a1f1f" })
set_highlight("VGitHunkChange", { bg = "#1f252a" })
set_highlight("VGitHunkAddSign", { fg = colors.sage })
set_highlight("VGitHunkRemoveSign", { fg = colors.red })
set_highlight("VGitHunkChangeSign", { fg = colors.blue })
set_highlight("VGitHistoryHeader", { fg = colors.amber, style = "bold" })
set_highlight("VGitHistoryEntry", { fg = colors.fg })
set_highlight("VGitHistoryEntryAuthor", { fg = colors.blue })
set_highlight("VGitHistoryEntryCommittedOn", { fg = colors.fg_dim })
set_highlight("VGitBlame", { fg = colors.fg_dim, style = "italic" })
set_highlight("VGitBlameLoading", { fg = colors.amber })
set_highlight("VGitBlameError", { fg = colors.red })

-- Lazygit
set_highlight("LazyGitFloat", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("LazyGitBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("LazyGitTitle", { fg = colors.amber, style = "bold" })
set_highlight("LazyGitSelectedLine", { bg = colors.bg_light })
set_highlight("LazyGitStagedFile", { fg = colors.sage })
set_highlight("LazyGitUnstagedFile", { fg = colors.blue })
set_highlight("LazyGitUntrackedFile", { fg = colors.amber })
set_highlight("LazyGitConflictFile", { fg = colors.red })
set_highlight("LazyGitBranch", { fg = colors.amber, style = "bold" })
set_highlight("LazyGitRemote", { fg = colors.blue })
set_highlight("LazyGitCommit", { fg = colors.amber_dim })
set_highlight("LazyGitCommitMessage", { fg = colors.fg })
set_highlight("LazyGitCommitAuthor", { fg = colors.blue })
set_highlight("LazyGitCommitDate", { fg = colors.fg_dim })

-- Rest.nvim
set_highlight("RestText", { fg = colors.fg })
set_highlight("RestMethod", { fg = colors.amber, style = "bold" })
set_highlight("RestUrl", { fg = colors.blue, style = "underline" })
set_highlight("RestHeader", { fg = colors.sage })
set_highlight("RestHeaderKey", { fg = colors.amber })
set_highlight("RestHeaderValue", { fg = colors.fg })
set_highlight("RestBody", { fg = colors.fg })
set_highlight("RestJson", { fg = colors.sage })
set_highlight("RestXml", { fg = colors.amber_dim })
set_highlight("RestHtml", { fg = colors.blue })
set_highlight("RestStatus", { fg = colors.fg_dim })
set_highlight("RestStatusSuccess", { fg = colors.sage })
set_highlight("RestStatusRedirect", { fg = colors.amber })
set_highlight("RestStatusClientError", { fg = colors.red })
set_highlight("RestStatusServerError", { fg = colors.red })
set_highlight("RestTime", { fg = colors.fg_dim })
set_highlight("RestSize", { fg = colors.fg_dim })

-- HTTP syntax
set_highlight("httpMethod", { fg = colors.amber, style = "bold" })
set_highlight("httpUrl", { fg = colors.blue, style = "underline" })
set_highlight("httpProtocol", { fg = colors.amber_dim })
set_highlight("httpHeader", { fg = colors.sage })
set_highlight("httpHeaderName", { fg = colors.amber })
set_highlight("httpHeaderValue", { fg = colors.fg })

-- Kulala (http client)
set_highlight("KulalaMethod", { fg = colors.amber, style = "bold" })
set_highlight("KulalaUrl", { fg = colors.blue, style = "underline" })
set_highlight("KulalaHeader", { fg = colors.sage })
set_highlight("KulalaHeaderKey", { fg = colors.amber })
set_highlight("KulalaHeaderValue", { fg = colors.fg })
set_highlight("KulalaBody", { fg = colors.fg })
set_highlight("KulalaJson", { fg = colors.sage })
set_highlight("KulalaXml", { fg = colors.amber_dim })
set_highlight("KulalaHtml", { fg = colors.blue })
set_highlight("KulalaStatus", { fg = colors.fg_dim })
set_highlight("KulalaStatusSuccess", { fg = colors.sage })
set_highlight("KulalaStatusRedirect", { fg = colors.amber })
set_highlight("KulalaStatusClientError", { fg = colors.red })
set_highlight("KulalaStatusServerError", { fg = colors.red })
set_highlight("KulalaTime", { fg = colors.fg_dim })
set_highlight("KulalaSize", { fg = colors.fg_dim })
set_highlight("KulalaIcon", { fg = colors.amber })
set_highlight("KulalaBorder", { fg = colors.gray_1, bg = colors.bg_dark })
set_highlight("KulalaTitle", { fg = colors.amber, style = "bold" })
set_highlight("KulalaFloat", { fg = colors.fg, bg = colors.bg_dark })

-- DBUI
set_highlight("NotificationInfo", { fg = colors.blue })
set_highlight("NotificationWarning", { fg = colors.yellow })
set_highlight("NotificationError", { fg = colors.red })
set_highlight("NotificationHint", { fg = colors.sage_dim })

-- Dadbod (database)
set_highlight("dbui_connection", { fg = colors.amber, style = "bold" })
set_highlight("dbui_database", { fg = colors.blue, style = "bold" })
set_highlight("dbui_table", { fg = colors.sage })
set_highlight("dbui_column", { fg = colors.fg })
set_highlight("dbui_query", { fg = colors.amber_dim })
set_highlight("dbui_result", { fg = colors.fg })
set_highlight("dbui_result_header", { fg = colors.amber, style = "bold" })
set_highlight("dbui_result_odd", { bg = colors.bg_highlight })
set_highlight("dbui_result_even", { bg = colors.bg })
set_highlight("dbui_result_selected", { bg = colors.bg_light })
set_highlight("dbui_result_modified", { fg = colors.amber })
set_highlight("dbui_result_null", { fg = colors.fg_dim, style = "italic" })
set_highlight("dbui_result_number", { fg = colors.amber_dim })
set_highlight("dbui_result_string", { fg = colors.sage })
set_highlight("dbui_result_boolean", { fg = colors.amber_dim })
set_highlight("dbui_result_date", { fg = colors.blue })
set_highlight("dbui_result_time", { fg = colors.blue_dim })
set_highlight("dbui_result_timestamp", { fg = colors.blue })
set_highlight("dbui_result_binary", { fg = colors.amber })
set_highlight("dbui_result_other", { fg = colors.fg })

-- SQL syntax
set_highlight("sqlKeyword", { fg = colors.amber, style = "bold" })
set_highlight("sqlFunction", { fg = colors.blue })
set_highlight("sqlOperator", { fg = colors.fg_dim })
set_highlight("sqlStatement", { fg = colors.amber, style = "bold" })
set_highlight("sqlType", { fg = colors.blue })
set_highlight("sqlIdentifier", { fg = colors.fg })
set_highlight("sqlString", { fg = colors.sage })
set_highlight("sqlNumber", { fg = colors.amber_dim })
set_highlight("sqlComment", { fg = colors.fg_dim, style = "italic" })
set_highlight("sqlSpecial", { fg = colors.amber })

-- Dadbod-ui
set_highlight("dbui_save_prompt", { fg = colors.amber, style = "bold" })
set_highlight("dbui_connection_form", { fg = colors.fg })
set_highlight("dbui_connection_form_name", { fg = colors.amber })
set_highlight("dbui_connection_form_value", { fg = colors.fg })
set_highlight("dbui_connection_form_password", { fg = colors.amber_dim })
set_highlight("dbui_connection_form_error", { fg = colors.red })
set_highlight("dbui_connection_form_success", { fg = colors.sage })
set_highlight("dbui_connection_form_info", { fg = colors.blue })

-- Vim-dadbod-completion
set_highlight("DadbodCompletionItem", { fg = colors.fg })
set_highlight("DadbodCompletionItemKind", { fg = colors.blue })
set_highlight("DadbodCompletionItemMenu", { fg = colors.fg_dim })
set_highlight("DadbodCompletionItemDeprecated", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("DadbodCompletionItemMatch", { fg = colors.amber, style = "bold" })

-- Vim-test
set_highlight("TestPass", { fg = colors.sage, style = "bold" })
set_highlight("TestFail", { fg = colors.red, style = "bold" })
set_highlight("TestRunning", { fg = colors.blue })
set_highlight("TestSkipped", { fg = colors.amber })
set_highlight("TestFile", { fg = colors.blue })
set_highlight("TestDir", { fg = colors.blue_dim })
set_highlight("TestSuite", { fg = colors.amber, style = "bold" })
set_highlight("TestTime", { fg = colors.fg_dim })
set_highlight("TestOutput", { fg = colors.fg })
set_highlight("TestError", { fg = colors.red })
set_highlight("TestSuccess", { fg = colors.sage })
set_highlight("TestWarning", { fg = colors.yellow })
set_highlight("TestInfo", { fg = colors.blue })

-- Vim-ultest
set_highlight("UltestPass", { fg = colors.sage })
set_highlight("UltestFail", { fg = colors.red })
set_highlight("UltestRunning", { fg = colors.blue })
set_highlight("UltestBorder", { fg = colors.gray_1 })
set_highlight("UltestInfo", { fg = colors.blue })
set_highlight("UltestSummaryInfo", { fg = colors.blue })
set_highlight("UltestSummaryFile", { fg = colors.blue })
set_highlight("UltestSummaryNamespace", { fg = colors.amber })
set_highlight("UltestSummaryPass", { fg = colors.sage })
set_highlight("UltestSummaryFail", { fg = colors.red })
set_highlight("UltestSummaryRunning", { fg = colors.blue })
set_highlight("UltestMarked", { fg = colors.amber, style = "bold" })
set_highlight("UltestOutput", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("UltestOutputWin", { fg = colors.fg, bg = colors.bg_dark })
set_highlight("UltestShadow", { bg = colors.bg_dark })

-- Vim-vebugger
set_highlight("vebuggerBreakpoint", { fg = colors.red, style = "bold" })
set_highlight("vebuggerDisabledBreakpoint", { fg = colors.fg_dim })
set_highlight("vebuggerProgramCounter", { fg = colors.amber, style = "bold" })
set_highlight("vebuggerDisabledProgramCounter", { fg = colors.amber_dim })
set_highlight("vebuggerLog", { fg = colors.fg_dim })
set_highlight("vebuggerLogLine", { fg = colors.fg })
set_highlight("vebuggerLogTime", { fg = colors.amber_dim })
set_highlight("vebuggerLogLevel", { fg = colors.amber })
set_highlight("vebuggerLogSource", { fg = colors.blue })
set_highlight("vebuggerVariable", { fg = colors.fg })
set_highlight("vebuggerValue", { fg = colors.sage })
set_highlight("vebuggerType", { fg = colors.blue })
set_highlight("vebuggerFrame", { fg = colors.amber })
set_highlight("vebuggerFrameCurrent", { fg = colors.amber, style = "bold" })
set_highlight("vebuggerThread", { fg = colors.blue })
set_highlight("vebuggerThreadCurrent", { fg = colors.blue, style = "bold" })
set_highlight("vebuggerAsm", { fg = colors.fg_dim })
set_highlight("vebuggerAsmAddress", { fg = colors.amber_dim })
set_highlight("vebuggerAsmInstruction", { fg = colors.fg })
set_highlight("vebuggerAsmOperand", { fg = colors.sage })

-- Vim-spectator
set_highlight("SpecFile", { fg = colors.blue })
set_highlight("SpecNamespace", { fg = colors.amber })
set_highlight("SpecPassed", { fg = colors.sage })
set_highlight("SpecFailed", { fg = colors.red })
set_highlight("SpecPending", { fg = colors.amber })
set_highlight("SpecSkipped", { fg = colors.fg_dim })

-- Quickfix
set_highlight("qfFileName", { fg = colors.blue })
set_highlight("qfLineNr", { fg = colors.amber_dim })
set_highlight("qfError", { fg = colors.red })
set_highlight("qfWarning", { fg = colors.yellow })
set_highlight("qfInfo", { fg = colors.blue })
set_highlight("qfHint", { fg = colors.sage_dim })
set_highlight("qfSeparator", { fg = colors.gray_3 })
set_highlight("qfText", { fg = colors.fg })
set_highlight("qfTextError", { fg = colors.red })
set_highlight("qfTextWarning", { fg = colors.yellow })
set_highlight("qfTextInfo", { fg = colors.blue })
set_highlight("qfTextHint", { fg = colors.sage_dim })

-- Location list
set_highlight("locFileName", { fg = colors.blue })
set_highlight("locLineNr", { fg = colors.amber_dim })
set_highlight("locError", { fg = colors.red })
set_highlight("locWarning", { fg = colors.yellow })
set_highlight("locInfo", { fg = colors.blue })
set_highlight("locHint", { fg = colors.sage_dim })
set_highlight("locSeparator", { fg = colors.gray_3 })
set_highlight("locText", { fg = colors.fg })

-- Make
set_highlight("makeIdent", { fg = colors.fg })
set_highlight("makeSpecTarget", { fg = colors.amber, style = "bold" })
set_highlight("makeTarget", { fg = colors.blue })
set_highlight("makeCommands", { fg = colors.fg })

-- CMake
set_highlight("cmakeCommand", { fg = colors.amber, style = "bold" })
set_highlight("cmakeCommandConditional", { fg = colors.amber })
set_highlight("cmakeCommandRepeat", { fg = colors.amber })
set_highlight("cmakeCommandDeprecated", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("cmakeCommandManuallyAdded", { fg = colors.amber_dim })
set_highlight("cmakeArguments", { fg = colors.fg })
set_highlight("cmakeKWargs", { fg = colors.sage })
set_highlight("cmakeVariable", { fg = colors.fg })
set_highlight("cmakeVariableValue", { fg = colors.sage })
set_highlight("cmakeEnvironment", { fg = colors.blue })
set_highlight("cmakeGeneratorExpression", { fg = colors.amber_dim })
set_highlight("cmakeGeneratorExpressions", { fg = colors.amber_dim })
set_highlight("cmakeProperty", { fg = colors.blue })
set_highlight("cmakeKWprop", { fg = colors.blue })
set_highlight("cmakeKWpropDeprecated", { fg = colors.fg_dim, style = "strikethrough" })
set_highlight("cmakeModule", { fg = colors.blue })
set_highlight("cmakeString", { fg = colors.sage })
set_highlight("cmakeComment", { fg = colors.fg_dim, style = "italic" })
set_highlight("cmakeBracketArgument", { fg = colors.sage })
set_highlight("cmakeBracketComment", { fg = colors.fg_dim, style = "italic" })
set_highlight("cmakeTodo", { fg = colors.amber, bg = colors.bg_light, style = "bold" })

-- Makefile syntax
set_highlight("makeTarget", { fg = colors.blue, style = "bold" })
set_highlight("makeSpecTarget", { fg = colors.amber, style = "bold" })
set_highlight("makeCommands", { fg = colors.fg })
set_highlight("makeCommandError", { fg = colors.red })
set_highlight("makeDefine", { fg = colors.amber })
set_highlight("makeStatement", { fg = colors.amber, style = "bold" })
set_highlight("makeIdent", { fg = colors.fg })
set_highlight("makePreCondit", { fg = colors.amber_dim })
set_highlight("makeInclude", { fg = colors.amber_dim })
set_highlight("makeFirstLine", { fg = colors.fg_dim })
set_highlight("makeComment", { fg = colors.fg_dim, style = "italic" })
set_highlight("makeDString", { fg = colors.sage })
set_highlight("makeSString", { fg = colors.sage })
set_highlight("makeBString", { fg = colors.sage })
set_highlight("makeError", { fg = colors.red })
set_highlight("makeExport", { fg = colors.amber })
set_highlight("makeOverride", { fg = colors.amber })
set_highlight("makeAutoVar", { fg = colors.amber_dim })
set_highlight("makeImplicit", { fg = colors.blue })
